### ISSUE TITLE
issue deploying vue frontend changes

### ISSUE THREAD

**Issue by vishalhkd** [tiangolo/full-stack-fastapi-postgresql#11]
I am new to Docker containerizations. Had the application built and running using docker. The backend changes I make are getting deployed correctly - verified through the swagger docs. However, i am not able to deploy any changes made to the frontend application.

I made a change to the admin view and added a new column to the table. Followed that up with "docker-compose up -d". I expected to see the change to the UI when ready, but that did not happen. The UI is still the same without the new column I added.

**Comment by kurtrottmann** [comment]
Hi, I think this behaviour is normal as mentioned in [README.md](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/README.md):

> For example, the directory with the backend code is mounted as a Docker "host volume" (in the file docker-compose.dev.volumes.yml), mapping the code you change live to the directory inside the container. That allows you to test your changes right away, without having to build the Docker image again.

While for Frontend developement it is recomended to use a live server (`npm run serve`).

> Notice that this live server is not running inside Docker, it is for local development, and that is the recommended workflow. Once you are happy with your frontend, you can build the frontend Docker image and start it, to test it in a production-like environment. But compiling the image at every change will not be as productive as running the local development server.

If you don't want to use the live server and see your changes, you must to destroy the frontend container and recreate it each time (`docker stop frontend_container_name`, `docker rm frontend_container_name`, `docker-compose up -d`).

**Comment by tiangolo** [comment]
Thanks @kurtrottmann !

@vishalhkd if you are running your frontend in the Docker container, you need to build the image first `docker-compose build` and then you can `docker-compose up -d`.

But it will take longer than developing locally, and won't do live reloads as with Vue CLI. My suggestion is to install Vue CLI and run the UI `vue ui`, and run your project from there during development. It's normally a lot more efficient.

**Comment by Nonameentered** [comment]
Hi @tiangolo, I've been able to run the live server using both `npm run serve` and `vue ui` methods, but I can't figure out how to see/test changes outside of the log in page doing this, since I am not connected with the backend for functions like authentication. Am I missing some step that would make testing the frontend in this way more functional?
