### ISSUE TITLE
How to run Jupyter notebooks on local dev?

### ISSUE THREAD

**Issue by pingu1m** [tiangolo/full-stack-fastapi-postgresql#110]
I noticed in the pipfile and on few docker-compose files the presence of the Jupyter package and some code mentioning Notebooks. I was wondering if anyone know how get it running on local development. Thanks.

**Comment by ebreton** [comment]
Hi @pingu1m 

I just run `docker-compose exec backend bash -c \$$JUPYTER`

... which means that the command stored in the `$JUPYTER` env var is going to be executed in a `backend` container

In return, the container logs will display an URL, which is the entry point to the Jupyter server.

Finally, I just copy paste this URL in Visual Code Studio... and that's it...

There are more information in the README section about it : Live development with Python Jupyter Notebooks

**Comment by pingu1m** [comment]
@ebreton I did not find any section about Live development with Python Jupyter Notebooks. Which README are you talking about? Thanks for the answer.

**Comment by ebreton** [comment]
Hi @pingu1m , in the README from the cookiecutter directory: https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/README.md#live-development-with-python-jupyter-notebooks

**Comment by pingu1m** [comment]
@ebreton Thanks.

**Comment by robido** [comment]
Hi @ebreton @pingu1m I am trying to understand how Jupyter can be used in the project. Do you have any example? In the docs it says:

> You will have a full Jupyter Notebook running inside your container, that has direct access to your database by the name container name, etc. So, you can just copy your backend code and run it directly, without needing to modify it.

I think just a quick example on how to get the current users in the database would point me in the right path. Once I get it, I could do a PR to add extra notes in the README.md. Thanks.

**Comment by tiangolo** [comment]
Thanks for the help here @ebreton ! :cake: 

Thanks @pingu1m  for reporting back and closing the issue! :coffee: 

@robido one example could be integrating it with VS Code: https://code.visualstudio.com/docs/python/jupyter-support#_connect-to-a-remote-jupyter-server
