### ISSUE TITLE
Starlette's TestClient unused

### ISSUE THREAD

**Issue by Toreno96** [tiangolo/full-stack-fastapi-postgresql#111]
Hi,

The official [FastAPI's tutorial](https://fastapi.tiangolo.com/tutorial/testing/) recommends to use Starlette's TestClient in testing.

Why this project template is inconsistent with the above? Was there any specific design decision to omit TestClient in the backend tests and use `Requests` instead? 🤔

I made a fork where I successfully integrated TestClient, so if you want I will create PR.

**Comment by StephenBrown2** [comment]
Not the author/maintainer, so I can't say with authority, but PRs are probably welcome. :-)

**Comment by Toreno96** [comment]
> Not the author/maintainer, so I can't say with authority, but PRs are probably welcome. :-)

I suppose so, but before I create the PR, I would like to know this 😄:
> Why this project template is inconsistent with the above? Was there any specific design decision to omit TestClient in the backend tests and use Requests instead?

**Comment by paul121** [comment]
My understanding is that all of the @tiangolo cookie-cutter repos are ideally kept in "sync" as much as possible. So modifying the tests for the full-stack repo means modifying tests on all of the other FastAPI cookie-cutters.

But that doesn't mean a PR isn't welcome to start that process and let others see how you've implemented @Toreno96 ! This would be very useful :smile:

**Comment by tiangolo** [comment]
Thanks for the help here everyone!

So, yes, I would like to have the tests using the `TestClient`, and in fact, get rid of the extra testing container.

It is set up this way because this project generator inherited a lot of the code from my previous project generator for Flask (predating FastAPI).

**Comment by hardbyte** [comment]
I believe this is fully addressed by #160 and can be closed.

**Comment by Toreno96** [comment]
> I believe this is fully addressed by #160 and can be closed.

That's true, thanks for the reminder. I'm closing the issue.
