### ISSUE TITLE
Works on one computer but not the other

### ISSUE THREAD

**Issue by johanek2** [tiangolo/full-stack-fastapi-postgresql#112]
I have been trying to debug this for a couple of days but without any luck.

 **What I did**
I took this project and applied some bug fixes from the issues here and then it worked fine. I made some minor modifications and added an endpoint to handle the computationally heavy requests i expect. All of this works perfectly on my computer.

**Problem**
I have the project in source control and I want to run it in the cloud and on a friends computer. I pull the project and build it, everything seams to work fine but when I go to localhost:80 all i see is an Apache 2 test page. If i go to localhost:8090 I see the Traefik page and can click on the backend-frontend-lodapi url which takes me to http://172.18.0.3/login where I can enter my login details but I can't login. From the logs it doesn't seam like any traffic is reaching the backend.

I did attach a filtered log here, unfortunate it is still quite long because I didn't know what to look for any more. It looks a little weird in the beginning and the end but I'm not sure.
[hello2.log](https://github.com/tiangolo/full-stack-fastapi-postgresql/files/4186715/hello2.log)

Maybe this means anything:
```
proxy_1          |0m time="2020-02-11T15:03:42Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" 
proxy_1          |0m time="2020-02-11T15:03:42Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL"
proxy_1          |0m time="2020-02-11T15:03:42Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" 
proxy_1          |0m time="2020-02-11T15:03:42Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" 
proxy_1          |0m time="2020-02-11T15:03:45Z" level=debug msg="'502 Bad Gateway' caused by: proxyconnect tcp: dial tcp 172.19.80.191:3128: connect: no route to host"
proxy_1          |0m time="2020-02-11T15:03:45Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://172.19.0.8:80, code: 502, Length: 11, duration: 3.060368573s"
proxy_1          |0m time="2020-02-11T15:03:45Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" 
proxy_1          |0m time="2020-02-11T15:03:45Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" 
proxy_1          |0m time="2020-02-11T15:03:45Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" 
proxy_1          |0m 172.19.0.1 - - [11/Feb/2020:15:03:42 +0000] "POST /api/v1/login/access-token HTTP/1.1" 502 11 "http://172.19.0.4/login" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" 2 "PathPrefix-api-docs-redoc-0" "http://172.19.0.8:80" 3060ms
```

Thanks

**Comment by Shackelford-Arden** [comment]
You're seeing this issue come up on the friends computer? Kind of sounds like they have the Apache web server up and running on their machine, amongst some other potential differing configurations.

- Is Apache up and running on this other machine?
- If it is, I'd double check it's config and see if it's proxying anything.

**Comment by tiangolo** [comment]
Yeah, that looks pretty much what @Shackelford-Arden says. It's most probably not related to this project at all (Apache is not used here in any place).

So it's probably that they have some Apache installed (maybe a XAMPP or something).
