### ISSUE TITLE
Exposing ports for docker swarm?

### ISSUE THREAD

**Issue by ascherbakhov** [tiangolo/full-stack-fastapi-postgresql#116]
Hi, there!

I had one issue with deploying stack to docker swarm: all containers inside swarm is accessed to each other since they are deployed without any errors. But I cannot access backend or frontend from external(e.g. browser) due to connection refused error, though after deploying through docker compose it works ok.

Later I realized that I should check listen ports through netstat, and I didnt find 80 port here. After that I found that in deploy script there are not any compose  *ports.yml file, that if I understand correctly help to expose appropriate ports for stack deploy. But docker compose use docker-compose.dev.ports.yml.

So, maybe docker-compose.deploy.ports.yml should be added to repo and to deploy.sh? Any other missed configs in deploy.sh? 

Thank you in advance!

**Comment by ascherbakhov** [comment]
I've found this issue
https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/78

What way of dealing with it would be the best?
I'm going to create pull request fixing it

**Comment by mocsar** [comment]
I have the same problem. Are the docker-compose.deploy.ports.yml and docker-compose.deploy.volumes.yml files missing?

**Comment by laurentS** [comment]
I had a similar issue. I ended up adding
```
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
```
under the `proxy` service. You can add it in a `docker-compose.deploy.ports.yml` file or elsewhere, as long as it's in the *deploy* combined `docker-compose` file.

**Comment by tiangolo** [comment]
Hmm, nope, that's the whole point, that you don't expose the ports of your app publicly but through a Traefik load balancer with Traefik that can handle HTTPS for you. And you don't expose anything publicly that could be a security risk.

If you are deploying with pure `docker-compose` instead of `docker stack` using https://dockerswarm.rocks , then you can update the local Docker Compose files to listen on those ports.

**Comment by laurentS** [comment]
@tiangolo can you confirm that if you deploy this stack template with the https://dockerswarm.rocks setup, you are expecting to have 2 separate traefik containers? My understanding is that you have:
- `traefik` that is public facing (the one in https://dockeswarm.rocks)
- `proxy` coming from this template which does not expose anything publicly (as it sits behind `traefik`)
Is this correct?
This has really confused me (as the comment above shows).

**Comment by hiteshgoyal18** [comment]
`ERROR: Invalid interpolation format for "networks" option in service "flower": "${TRAEFIK_PUBLIC_NETWORK?Variable not set}"
`
Getting this error on running `docker-compose up -d`
Any suggestions would be appreciated.
