### ISSUE TITLE
poetry instead of Pipfile

### ISSUE THREAD

**Issue by RCheese** [tiangolo/full-stack-fastapi-postgresql#123]
subj

**Comment by jlugao** [comment]
+1 on poetry, however, I am not sure how to go about deployment with it, might have to generate a requirements.txt for that

**Comment by RCheese** [comment]
> +1 on poetry, however, I am not sure how to go about deployment with it, might have to generate a requirements.txt for that

Poetry might generate requirements.txt out of the box since 1.0 version for docker install or PyCharm indexing and etc. In case of pipfile you need a another tool as requirementslib for this

**Comment by StephenBrown2** [comment]
Poetry 1.x will generate a requirements.txt:
https://python-poetry.org/docs/cli/#export
```
poetry export -f requirements.txt > requirements.txt
```

**Comment by RCheese** [comment]
> Poetry 1.x will generate a requirements.txt:
> https://python-poetry.org/docs/cli/#export
> 
> ```
> poetry export -f requirements.txt > requirements.txt
> ```

I wrote the same)

**Comment by laurentS** [comment]
I have modified my project to use `poetry`, and I changed the dockerfiles to do the following:
```bash
COPY ./backend/app/pyproject.toml ./backend/app/poetry.lock /app/
RUN cd /app && $HOME/.poetry/bin/poetry config virtualenvs.create false && $HOME/.poetry/bin/poetry install
```
The `config virtualenvs.create false` part disables the use/creation of a venv by poetry, so it installs everything in the "main" python inside the docker images. While not required, I feel that using the same tool everywhere makes more sense.

As a side note, I use a custom base image with most of my python dependencies in it to save time in CI, and there is a [bug in poetry](https://github.com/python-poetry/poetry/issues/1882) that reinstalls everything even if included in the base image, but it still works.

**Comment by lucawen** [comment]
this will be really great and simple to change!

**Comment by tiangolo** [comment]
Yep. I want to migrate this to Poetry :smile: 

I just haven't had the time yet.

**Comment by mrbox** [comment]
I'll create a PR for this, most likely this week. @tiangolo what do you think about also changing `backend.dockerfile` to install dependencies using Poetry instead of raw `pip install ...`?

**Comment by tiangolo** [comment]
We now have Poetry, and it's integrated into the `Dockerfiles` as well. :rocket: 

Thanks @RCheese for the idea and PR!
