### ISSUE TITLE
Cookiecutter Windows Bug in worker-start.sh: CRLF Linebreaks

### ISSUE THREAD

**Issue by Sieboldianus** [tiangolo/full-stack-fastapi-postgresql#13]
First, many thanks for this project! I am lookin forward to testing it.

I had some problems getting it to run on Windows and found the source (it was me). Even though it was my fault, I thought a note in the readme could be added for other users:

The backend would not start because linebreaks in `worker-start.sh` (and other bash-files) were CRLF (Windows), and not LF (Linux). In `docker-compose logs` this would appear as `invalid command \r` etc.

I used cookiecutter in Windows with `cookiecutter https://github.com/tiangolo/full-stack-fastapi-postgresql`, which issued CRLF linebreaks. Once using cookiecutter from WSL bash in Ubuntu, everything worked fine!

I think it generally a good recommendation to use docker-compose, and docker from WSL bash (connected through Windows Docker daemon running on localhost); and set VSCode (if used from Windows), to use LF in global settings with `"files.eol": "\n"`.

**Comment by tiangolo** [comment]
Thanks! I think it's a problem in Cookiecutter itself, this PR seems to fix it: https://github.com/audreyr/cookiecutter/pull/1159

**Comment by tiangolo** [comment]
This should be fixed by https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/149 🎉
