### ISSUE TITLE
Deploy issue: db shutdown automatically

### ISSUE THREAD

**Issue by binfeng** [tiangolo/full-stack-fastapi-postgresql#132]
I tried `deploy.sh` and it successfully deployed, but the frontend is receiving 502 error.

I used `docker service logs db` to find out db is getting shutdown after started:

> 2020-03-22 02:14:08.775 UTC [1] LOG:  database system is ready to accept connections
> 2020-03-22 02:14:12.811 UTC [1] LOG:  received smart shutdown request
> 2020-03-22 02:14:12.821 UTC [1] LOG:  background worker "logical replication launcher" (PID 33) exited with exit code 1
> 2020-03-22 02:14:12.822 UTC [28] LOG:  shutting down
> 2020-03-22 02:14:12.957 UTC [1] LOG:  database system is shut down

The other containers also get shutdown maybe due to db issue.

Is anywhere I can dig further to find the root cause, e.g. port is occupied, etc?
Thanks!

**Comment by binfeng** [comment]
Dev environment is working for me, but not production after deployed.

**Comment by tiangolo** [comment]
Hi @binfeng , I assume you solved your issue since you closed it, right?
