### ISSUE TITLE
Run on arm

### ISSUE THREAD

**Issue by ssspeq** [tiangolo/full-stack-fastapi-postgresql#134]
For anyone else that wants to get this running on arm like I did, you should be able to use my multiarch images for this project.

Replace:

tiangolo/uvicorn-gunicorn-fastapi:python3.7

with

ssspeq/uvicorn-gunicorn-fastapi:python3.7

in backend.dockerfile and replace:

tiangolo/node-frontend:10 as build-stage

with

ssspeq/node-frontend:10 as build-stage

in the frontend dockerfile.

Now it should work on arm and x86. Puppeteer is not installed in the arm versions, only for x86.

**Comment by tiangolo** [comment]
Cool! Thanks for sharing! :rocket:

**Comment by eugsokolov** [comment]
would be great to have support for arm from the main branch
