### ISSUE TITLE
Is it possible to use a wildcard * domain with Traefik?

### ISSUE THREAD

**Issue by tsh356** [tiangolo/full-stack-fastapi-postgresql#142]
Can I set TRAEFIK_TAG = "*.mydomain.com" to enable SSL on app.mydomain.com and customer.mydomain.com?

**Comment by tiangolo** [comment]
Not with this setup as it uses the Let's Encrypt HTTP challenges.

You can have wildcard TLS certificates with Let's Encrypt but only with the DNS challenges, so you have to add quite some extra setup: https://letsencrypt.org/docs/faq/#does-let-s-encrypt-issue-wildcard-certificates
