### ISSUE TITLE
Keeping Cookiecutter Updated?

### ISSUE THREAD

**Issue by btotharye** [tiangolo/full-stack-fastapi-postgresql#146]
So I'm kind of new to cookiecutter and I'm really liking how much this repo has to start with (Minus all the docker compose files which I am going to clean up :) ) and I wanted to start ensuring I keep my project updated and push stuff back in.

Is there a easy way with cookiecutter to do this or am I at the mercy of having a fork I keep updated then occasionally redo the template and have to go through my code checking for updates?

Just trying to see how others are doing this and what works best for you.

**Comment by tiangolo** [comment]
I imagine you solved your problem, so thanks for reporting back and closing the issue :+1: 

Anyway, check the docs about project updating/re-generating: https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/README.md#project-generation-and-updating-or-re-generating
