### ISSUE TITLE
Uploading Coverage Data

### ISSUE THREAD

**Issue by btotharye** [tiangolo/full-stack-fastapi-postgresql#147]
So I'm sure its related to running in docker and how this is setup but if you are trying to upload to say codecov what is the best way to get this working?  Right now it appears their isn't a volume mount so you can't use say the github actions for it without having that mount and for some reason doing something like below in the `test.sh` seems to create the xml file in the root of the container not the app dir and even then I doubt that is mapped out so no matter what I try the codecov bash can't find it.

```
docker-compose -f docker-stack.yml exec -T backend-tests /tests-start.sh --cov-config .coveragerc --cov-report=xml "$@"

```

Has anyone already setup any type of coverage reporting and would be willing to share your setup?  I'm sure this is how the volume mounting is working and I'm still investigating it.

Thanks

**Comment by tiangolo** [comment]
I assume you solved your problem, so, thanks for coming back to close the issue :+1:
