### ISSUE TITLE
What about casting CRUD returned value to pydantic models ?

### ISSUE THREAD

**Issue by ebreton** [tiangolo/full-stack-fastapi-postgresql#15]
I have implemented 
- a pydantic `City` model (and some extra models for the updates, creations as suggested in the [tutorial](https://fastapi.tiangolo.com/tutorial/sql-databases/)). 
- a SQLalchemy `DBCity` model

I would like the `crud.get` method  to return the `City` model and not the `DBCity`.

More important, I would like the casting from DBCity to City to be done automatically, with something like

```
def get(db_session, city_id: int) -> Optional[City]:
    return db_session.query(DBCity).get(city_id)
```

The code above does not make any casting, and behaves as follow:

```
def get(db_session, city_id: int) -> Optional[DBCity]:
    return db_session.query(DBCity).get(city_id)
```

What do you think of this behavior ? 

Wouldn't it be nice to have an auto-casting like the ones of the API ?

**Comment by ebreton** [comment]
After a few days of playing around, I finnaly think that it is appropriate that crud methods returns SQLAlchemy objects. The casting to pydantic objects should be done later on by the layers above

**Comment by tiangolo** [comment]
Cool, thanks for reporting back and closing the issue.
