### ISSUE TITLE
docker-compose initial run Error

### ISSUE THREAD

**Issue by Rigel772** [tiangolo/full-stack-fastapi-postgresql#154]
After generating project with cookiecutter when I run 
`docker-compose up -d `
I am getting this error:
`ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml`

Project folder looks like this: https://github.com/Rigel772/fastapi-test
There is no docker-compose.yml file...
What am I doing wrong?
Thanks

**Comment by Rigel772** [comment]
I have run cookiecutter again and it generated docker-compose file this time :)

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue! :+1:
