### ISSUE TITLE
Poetry/Docker Issue

### ISSUE THREAD

**Issue by btotharye** [tiangolo/full-stack-fastapi-postgresql#157]
Correct me if I am wrong but with something like https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/backend.dockerfile#L13

Won't that prevent the dev dependencies for testing and stuff from ever working?  Maybe it should have a check similar to https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/backend.dockerfile#L19 to install dev dependencies or am I missing something?

Still kind of learning poetry so its possible I'm missing something but when I tried adding `pytest-cov` for example to the pyproject.toml as a dev dependency I can only seem to get it working outside the container so that led me to this.

So I am pretty sure this needs to be changed to something like this which I am trying:

```
RUN echo "$env" \
  && poetry install \
    $(if [ "$env" = 'prod' ]; then echo '--no-dev'; fi) \
    --no-interaction --no-ansi --no-root 
```

**Comment by btotharye** [comment]
this above seems to work but still not sure if more is needed since it seems like every time I run the test-local.sh now it installs all the dependencies each time.  Might just be how it will work since it takes it down each time, etc.

**Comment by tiangolo** [comment]
Hehe, yep, that's right.

I just finished updating all that today. There's now an `ARG` in the Dockerfiles that installs testing dependencies conditionally, for running the tests, or when developing locally.

Also, now that it uses the `TestClient`, there are new instructions about reporting test coverage in the generated docs.

**Comment by btotharye** [comment]
Ok great gonna close it out.
