### ISSUE TITLE
login credentials not accepted

### ISSUE THREAD

**Issue by jerodg** [tiangolo/full-stack-fastapi-postgresql#16]
I've run the install several times and each time the admin login does not accept my credentials.
Any thoughts?

**Comment by ebreton** [comment]
FIrst, you can double check that you are using the same credentials as in your `env-backend.env`file

````
FIRST_SUPERUSER=email
FIRST_SUPERUSER_PASSWORD=password
```

If everything is correct, you can then check that your credentials are in the DB (you can login to [pgadmin](http://localhost:5050) in order to do so, then add the DB server and connect to it, and finally drill down to the user table)

**Comment by jerodg** [comment]
Verified credentials I'm using are same as in env-backend.env

I'm running this on a remote server. I have opened all of the ports on the firewall. I am unable to access any of the pages listed in the readme except the front-end production login page.

I have the @ entry in my dns pointing to the servers ip.

**Comment by ebreton** [comment]
How have you deployed the stack on your remote server ?

**Comment by jerodg** [comment]
I ran the entire process on the remote server.

**Comment by tiangolo** [comment]
Thanks for your help @ebreton !

@jerodg can you see `yourdomain/docs`? If not, check the `backend` logs.

If you can see the docs page, login there (before trying to log in in the frontend). That way you are debugging fewer parts and isolating the problem.

**Comment by j3cc** [comment]
I want to chime in on this one.

I run everything locally and I am able to navigate to localhost:8080 for front-end or localhost:8080/docs . Both do not login with the credentials specified in cookiecutter. Also I am able to navigate to localhost:5050 for pgAdmin, but not able to login with any specified password / user. Both frontend and pgadmin say they don't have my specified user in the system, when i go to `recover password`.

How do I debug this @tiangolo ?

**Comment by wadkar** [comment]
@j3cc check if you can authorize yourself in the `/docs` page. If you can - then its probably frontend issue. Check console for any CORS related errors.

Check if both `./.env` and `./backend/.env` files have consistent domain. Of course, make sure it matches with your browser address bar -- I had set it to `dev.myapp.com` while accessing `myapp.com`.

Also check the documentation about CORS headers in the generated repository -- Chrome doesn't play nicely with `localhost` and CORS headers.

**Comment by jmugan** [comment]
I can log in everywhere but the frontend. It is the first superuser and first superuser password, right? I couldn't log in either in Chrome or Firefox, and when I try to get it to email me my password, it says my user doesn't exist. I'm sorry, I don't know much about this kind of thing, can anyone point me in the right direction?

**Comment by tiangolo** [comment]
Thanks for the thorough explanation @wadkar !

The best way to debug things is to first isolate the problem, check if it's in the backend or in the frontend.

Try to login only in the `/docs`, without using the frontend. If that doesn't work, you know there's a problem in the backend that you have to solve first. Then try to login in the frontend. If that doesn't work (and the backend *does* work), then there's a problem in the frontend. But the first step is to isolate the problem.
