### ISSUE TITLE
Error generating Project

### ISSUE THREAD

**Issue by J88G** [tiangolo/full-stack-fastapi-postgresql#162]
- on MacOs
- using all the default values

```
traefik_constraint_tag_staging [stag.base-project.com]:
traefik_public_constraint_tag [traefik-public]:
flower_auth [admin:changethis]:
sentry_dsn []:
docker_image_prefix []:
docker_image_backend [backend]:
docker_image_celeryworker [celeryworker]:
docker_image_frontend [frontend]:  
File "/var/folders/w7/6vhbg9hs66nfdn37x62bb4vm0000gn/T/tmpFWZnq7.py", line 4
    path: Path
        ^
SyntaxError: invalid syntax
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

- Project is not generated.

**Comment by fancar** [comment]
The same thing (on Ubuntu 18.04 if it's nesessary) 

> docker_image_frontend [frontend]: 
>   File "/tmp/tmpSmDZFl.py", line 4
>     path: Path
>         ^
> SyntaxError: invalid syntax
> ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
> Hook script failed (exit status: 1)

**Comment by fancar** [comment]
(ubuntu 18.04, python 3.6.9, Cookiecutter 1.6.0, Python 2.7.17) I've faced the same issue. 

the hook is for replacing the end of lines in all .sh scripts. So I just removed this part code 

~/.cookiecutters/full-stack-fastapi-postgresql/hooks/post_gen_project.py

It appears after this step is  reached:  docker_image_celeryworker [celeryworker]: 

I hope it will help.

**Comment by cristeaadrian** [comment]
Same issue, installed cookiecutter using `sudo apt install cookiecutter`, because the pip versions didn't seem to install executables. It's probably out of date.

**Comment by lmendozasv** [comment]
Same issue on OS X, all packages updated but doesn't work :(

**Comment by tiangolo** [comment]
All this project uses and depends on Python 3.6. You should probably install `cookiecutter` with your Python 3.6.

Maybe something like this:

```console
$ python3.6 -m pip install cookiecutter
```

Or even better, with `pipx` to make sure you have your an independent environment for it: https://github.com/pipxproject/pipx

If you need to learn more about environments, check this: https://snarky.ca/a-quick-and-dirty-guide-on-how-to-install-packages-for-python/
