### ISSUE TITLE
Centralized independent authentication micro-service 

### ISSUE THREAD

**Issue by vishalkhondre** [tiangolo/full-stack-fastapi-postgresql#163]
Please note, this is not any defect or any issue as such.
I am building micro-services based application using FastAPI and I was referring to your full stack postgresql example. Its great example however I'm not very sure on how I can separate out authentication and authorization service so that it can be used centrally by many other micro-services. Would you be able to share any thoughts or pointers or guide me so that I can take it forward? Thank you!

**Comment by chris-allnutt** [comment]
@vishalkhondre as long as the service dispatching JWT's shares the same secret you should be fine.  While the individual consuming endpoints to validate the token would be fine, you'll still need to decide how you want to handle claims in the central auth service.

**Comment by vishalkhondre** [comment]
@chris-allnutt and @wedwardbeck - Thank you so much for all your help and guidance (here and https://gitter.im/tiangolo/fastapi).

I was able to implement it. In microservcies other than user, I'm able to validate JWT token that has been sent to frontend in the first place while authentication. As part of JWT validation token I'm only doing two things - 
1. successfully decode token using secret key
2. Checking if user is valid and active with the help of userid which is part of JWT token

**Comment by vishalkhondre** [comment]
This was not an issue. I was seeking help on "How-to" and response from @chris-allnutt and @wedwardbeck  helped me. Thank you so much for all your help and guidance (here and https://gitter.im/tiangolo/fastapi). Closing this issue.

**Comment by tiangolo** [comment]
Thanks for the help here @chris-allnutt ! :clap: :bow: 

Thanks for reporting back and closing the issue @vishalkhondre  :+1:
