### ISSUE TITLE
backend is not starting (on linux)

### ISSUE THREAD

**Issue by Rigel772** [tiangolo/full-stack-fastapi-postgresql#167]
docker-compose logs backend returns:
```backend_1       | Checking for script in /app/prestart.sh
backend_1       | Running script /app/prestart.sh
backend_1       | INFO:__main__:Initializing service
backend_1       | INFO:__main__:Starting call to '__main__.init', this is the 1st time calling it.
backend_1       | INFO:__main__:Service finished initializing
backend_1       | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
backend_1       | INFO  [alembic.runtime.migration] Will assume transactional DDL.
backend_1       | Traceback (most recent call last):
backend_1       |   File "/app/app/initial_data.py", line 3, in <module>
backend_1       |     from app.db.init_db import init_db
backend_1       |   File "/app/app/db/init_db.py", line 3, in <module>
backend_1       |     from app import crud, schemas
backend_1       |   File "/app/app/crud/__init__.py", line 2, in <module>
backend_1       |     from .crud_user import user
backend_1       |   File "/app/app/crud/crud_user.py", line 5, in <module>
backend_1       |     from app.core.security import get_password_hash, verify_password
backend_1       |   File "/app/app/core/security.py", line 4, in <module>
backend_1       |     from jose import jwt
backend_1       | ModuleNotFoundError: No module named 'jose'
```
tried from /app/:
`poetry add python-jose`
but it does not make any difference...
Any ideas? I am quite new to python and docker.... it may be something silly...
(tried to generate cookiecutter project with all defaults and it is all the same...)
Thanks

**Comment by Rigel772** [comment]
Dont understand it... Docker by design is supposed to work everywhere.. How ti is possible to get ModuleNotFoundError? Is it possible it works for anybody else but me??

**Comment by chris-allnutt** [comment]
Are you using the base container provided by the fastspi fullstqck project?   There's some weird issues with open id connect, openssl and some python base Docker images

@Rigel772 docker is consistent if you tag specific versions for your builds, much like server not all projects do this tending towards always using :latest 

Potentially try using an explicitly tagged version of the Python full stack container, maybe the base it's built on changed something.

**Comment by Rigel772** [comment]
Thanks for your advice @chris-allnutt 
Indeed the backend part of docker-compose is with "latest" tag....
` backend:
    image: '${DOCKER_IMAGE_BACKEND}:${TAG-latest}'`
How do I know what versions to use?
Could you give me working docker-compose file?
...or where can I find it?
Thanks again

**Comment by Rigel772** [comment]
No one??

**Comment by tiangolo** [comment]
@Rigel772 please generate a new project from scratch, follow the instructions in the generated README without modifications, and make sure it all works correctly.

Then you can check and compare which things are different between your project and the new one generated from scratch.
