### ISSUE TITLE
Lose Swagger Auth on Page Reload

### ISSUE THREAD

**Issue by btotharye** [tiangolo/full-stack-fastapi-postgresql#169]
Is it expected behavior for the Swagger docs auth lock to reset every time I refresh or reload the page and have to login again?

**Comment by chris-allnutt** [comment]
Yes.  It doesn't use session or local storage by design.  There's currently a feature request and PR in the swagger-ui project to add this, FastAPI just uses swagger-ui on that page.

**Comment by chris-allnutt** [comment]
https://github.com/swagger-api/swagger-ui/issues/5803

**Comment by btotharye** [comment]
gotcha I'll close this then.

**Comment by tiangolo** [comment]
Thanks for the help here @chris-allnutt ! :clap: :bow: 

Thanks for reporting back and closing the issue @btotharye  :+1:
