### ISSUE TITLE
[Question] Postgres does not keep data after docker-compose down

### ISSUE THREAD

**Issue by maverick42** [tiangolo/full-stack-fastapi-postgresql#170]
Hi,

I installed this stack and it works really well. I only have one problem.
When I execute commands 'docker-compose down' and then 'docker-compose up -d' I lose all my data in the database. This may be a normal docker behaviour but I want to keep my data. I think I need to name the volumes so that they are persistent but I don't understand how to do it. 

Can you help me ?

Regards 
Frédérik

**Comment by Nonameentered** [comment]
Since the latest updates, the volume with the data should already be named and persisted when you do `docker-compose down` and `docker-compose up -d`. Do you get anything named when you do `docker volume ls`?

**Comment by tiangolo** [comment]
As @Nonameentered says, it uses a Docker volume, it should be persisted unless you do `docker-compose down -v`.

Could you check that @maverick42 ?

**Comment by maverick42** [comment]
Hi @Nonameentered, @tiangolo 

Sorry for the delay. I've checked and I only have (many) volumes with GUIDs. I still don't have enough knowledge about how docker/docker-composer works

![image](https://user-images.githubusercontent.com/2311642/84109986-461be800-aa24-11ea-9ae6-6432901b3aa3.png)

Maybe my configuration is old and my volumes are not named?

![image](https://user-images.githubusercontent.com/2311642/84110327-f1c53800-aa24-11ea-954f-6f60b4b9ffb4.png)

Thanks,

**Comment by tiangolo** [comment]
Yeah, that `app-db-data` is a "named volume", it should be storing your data even if you do `docker-compose down` that stops and eliminates the containers.

`docker-compose down -v` stops and eliminates the containers AND eliminates named volumes like this one.

So, that should be preserved...

Could you try doing this?:

* generating a fresh new project, from scratch
* start it up with `docker-compose up -d`
* add some data, e.g. a new user
* confirm with pgadmin that the data is stored in the DB
* stop the stack with `docker-compose down`
* start it up again with `docker-compose up -d`
* confirm that the data (the new user) is still in the DB with pgadmin
