### ISSUE TITLE
Evaluate async db interactions, instead of straight sql alchemy

### ISSUE THREAD

**Issue by chris-allnutt** [tiangolo/full-stack-fastapi-postgresql#174]
Has the idea of incorporating something like gino into the default project been discussed at all?  I'm working on converting my own project to use it.  

With FastAPI being async based we lose concurrency by introducing blocking threads to any worker executions.

**Comment by mlaradji** [comment]
It might be cleaner* to use an async orm instead of sqlalchemy, and there may be speed improvements**, but it is not necessary. FastAPI (and python asyncio in general) allows you to run blocking code in their own threads. See for example (https://github.com/tiangolo/fastapi/issues/1066).

* if all your endpoints are async
** `asyncpg` for example seems to be much faster than `psycopg2`

**Comment by chris-allnutt** [comment]
I am aware of this, I'm suggesting it might be a good idea to look into async options, and I'd be happy to contribute towards it.  Most all the ORM code could be easily converted, to any number of alternative options.

It's great that fastAPI spawns threads for sync work loads, but every additional thread has a cost overall.

**Comment by tiangolo** [comment]
Yeah, the thing is that I don't see an obvious "best" option. So I ended up using what would probably be the simplest and most familiar option.

It would also show a simple and clear path to migrate an existing app with something like Flask to FastAPI, without making it look like you can only use async stuff with FastAPI.

At the same time, for a new project it would probably make sense to use the best possible option, but I also haven't found something that I consider the "absolute best".

Tortoise ORM has integrated Pydantic, which is great.
GINO is based on SQLAlchemy, so it's easy to use the same style of (I think) intuitive query filtering without magic keyword arguments (as would be with Django or Tortoise).
Encode/Databases is a more bare-bones option, so it would mean renouncing to ORM utilities.
Encode/ORM uses the same style from Django, with filtering based on magical keyword argument names, I would prefer the SQLAlchemy style with Python expressions.

Given that, I have ended up just leaving a simple default of the "most common" tool used, and then let everyone adapt to their own needs for each project.
