### ISSUE TITLE
Question: How what makes openapi aware of the need for auth, and know which routes to require authentication?

### ISSUE THREAD

**Issue by chris-allnutt** [tiangolo/full-stack-fastapi-postgresql#175]
I look at openapi.json and see that it describes required authentication for some routes, the routes have current_user = Depends in the routers, which then requires get user eventually going down to requiring an OAuth2PasswordBearer instance.

How does this make the openapi json aware of the need for auth, I would have thought there would be some kind of middleware registration, and then per route you would require or not require auth.

Can I get some clarification on how this works, because it all looks like magic to me right now.

**Comment by mlaradji** [comment]
Hey @chris-allnutt. I'm quite new to this project so I'm not sure if I'm 100% correct.

It looks like JWT's are used for authentication. The actual check is defined in [`deps.get_current_user`](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/bdc40a17f6f180ecba9fce79fb359a03f1d8409f/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/api/deps.py#L27). It is used for example in [`users.read_user_me`](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/bdc40a17f6f180ecba9fce79fb359a03f1d8409f/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/api/api_v1/endpoints/users.py#L79). This explains how authentication is required in the backend.

How does the OpenAPI spec know that authentication is required? Not sure. It looks like some FastAPI magic: `users.read_user_me` `Depends` on `deps.get_current_active_user`, which `Depends` on `OAuth2PasswordBearer`.

**Comment by mlaradji** [comment]
This looks like FastAPI magic :1st_place_medal:. From the documentation on `OAuth2PasswordBearer` in `https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/`:

> The OAuth2PasswordRequestForm is not a special class for FastAPI as is OAuth2PasswordBearer.
>
> OAuth2PasswordBearer makes FastAPI know that it is a security scheme. So it is added that way to OpenAPI.
>
> But OAuth2PasswordRequestForm is just a class dependency that you could have written yourself, or you could have declared Form parameters directly.
> 
> But as it's a common use case, it is provided by FastAPI directly, just to make it easier.

**Comment by chris-allnutt** [comment]
I think I finally found my answer, here, It's due to the Dependency injection implementation, the OAuth2asswordBearer alters route constraints, as @mlaradji pointed out https://fastapi.tiangolo.com/features/#dependency-injection

**Comment by tiangolo** [comment]
All these OAuth2 utilities depend on (or inherit) from a base special `OAuth2` class. FastAPI checks if the dependable is an instance of that class to extract the info for OpenAPI.

The `OAuth2` class has all the basic raw stuff, supporting all the OAuth2 options. Then the utility sub-classes fill the things relevant for each case so that you don't have to configure everything by hand, and maybe extracting credentials from a known place (e.g. the bearer token) but that's mostly it. :shrug: :smile:
