### ISSUE TITLE
[Discussion] event handlers or session

### ISSUE THREAD

**Issue by s0h3ck** [tiangolo/full-stack-fastapi-postgresql#181]
Hi community,

Among projects available online, I see two popular approaches: (1) event handlers with startup and shutdown, (2) session with sqlalchemy.

Project examples using approach one:
https://github.com/nsidnev/fastapi-realworld-example-app
https://testdriven.io/blog/fastapi-crud/

Project examples using approach two:
https://github.com/tiangolo/full-stack-fastapi-postgresql

What are the best practices or recommendations, and why?

Thanks!

**Comment by tiangolo** [comment]
The database connection with `databases` is a different thing than the SQLAlchemy session.

Databases is async, and if I remember correctly, autocommits by default. SQLAlchemy will create an automatic transaction and only commit once you do `db.commit()`, that's also why you would probably prefer to have an independent session per request using dependencies.
