### ISSUE TITLE
Front-end - Property or method "errors" is not defined

### ISSUE THREAD

**Issue by victorpergher** [tiangolo/full-stack-fastapi-postgresql#182]
Hi!

I have a problem on my front-end. When run the errors messages appears on console:
![image](https://user-images.githubusercontent.com/8138620/81574164-d6aace00-937b-11ea-8895-7668e10fff10.png)

The problem is: `errors` don't exists. This variable errors is used in fews locals on front-end, example: `errors.collect('email')`

What i define this `errors` variable?

Sorry for my english, is not my native language! :smile:

**Comment by victorpergher** [comment]
I have discovered the problem :smile: 
I have installed the veeValidate 3.x

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
