### ISSUE TITLE
Poetry install stuck

### ISSUE THREAD

**Issue by adrlud** [tiangolo/full-stack-fastapi-postgresql#188]
When i run build with docker-compose the install process get stuck when trying to download and install Poetry on Mac.

Looks like this in the terminal:

Successfully tagged frontend:latest
Building celeryworker
Step 1/15 : FROM python:3.7
 ---> 1164152aed87
Step 2/15 : WORKDIR /app/
 ---> Using cache
 ---> c75864aef5ed
Step 3/15 : RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python &&     cd /usr/local/bin &&     ln -s /opt/poetry/bin/poetry &&     poetry config virtualenvs.create false
 ---> Running in 81ad614b0c2e

**Comment by guaifish** [comment]
I have the same problem, running in docker for windows

**Comment by adrlud** [comment]
I downloaded the get-poetry.py file, ran it with python get-poetry.py --uninstall.

**Comment by tiangolo** [comment]
You can probably try to remove those lines, start a Docker container from an image without them, and use `docker exec` to start a `bash` session inside, and then run the commands by hand, to see what's happening.
