### ISSUE TITLE
Push Docker to Gitlab

### ISSUE THREAD

**Issue by MaxRichter** [tiangolo/full-stack-fastapi-postgresql#190]
Hi,

I have a problem with pushing the Docker file, to the Gitlab Container Registry for the backend and celery.

Under /backend, there is `backend.dockerfile` and `celeryworker.dockerfile`.

When I try to push to the Docker Repo with:
`docker build -t registry.gitlab.com/<user>/data-dashboard .`

unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/max/PycharmProjects/data-dashboard/backend/Dockerfile: no such file or directory

What I see, the [problem is the naming convention](https://stackoverflow.com/questions/35511604/docker-unable-to-prepare-context-unable-to-evaluate-symlinks-in-dockerfile-pat):

Can someone confirm this?

**Comment by tiangolo** [comment]
It seems that your problem is building the Docker image, not pushing it.

I guess first make sure your file `/home/max/PycharmProjects/data-dashboard/backend/Dockerfile` exists and is not a link to a file somewhere else.
