### ISSUE TITLE
Could you use vue-i18n in front?

### ISSUE THREAD

**Issue by Chise1** [tiangolo/full-stack-fastapi-postgresql#197]
I hope front can use vue-i18n then allow other langeuage.

**Comment by tiangolo** [comment]
Thanks for the suggestion, I have to do a lot of improvements and reactors here, but I have to start with SQLModel first. I don't think I'll be able to add more features to this project template, at least not before taking care of what's already there, so I'll pass on this suggestion for now. But thanks for the interest! :cake:
