### ISSUE TITLE
Is there exists step-by-step for full stack web developmemt tutorials based on fastapi?

### ISSUE THREAD

**Issue by tkianai** [tiangolo/full-stack-fastapi-postgresql#198]
Hi guys, I am a new comer in web development, is there exists some detailed tutorials for step-by-step instructions based on fastapi?

**Comment by tiangolo** [comment]
The first resource is the FastAPI docs, following the tutorial step by step you should get an idea of all the basic functionality.

It's also separated from the "Advanced User Guide" that covers additional or more complex ideas.

You can also check some links and blog posts in the external links section.

And also, recently TestDriven.io released a FastAPI course, and they are donating 10% back to FastAPI development :smile: ...if you prefer a full course.

**Comment by tkianai** [comment]
Thank you very much!
