### ISSUE TITLE
Many to Many Relationships, Best Practices

### ISSUE THREAD

**Issue by myfoostrong** [tiangolo/full-stack-fastapi-postgresql#209]
Hello, and first off thanks for fastapi, and this bootstrapping project. Have really loved the time I've spent so far re-building my API server in this framework.

This isn't 100% a fastapi issue, but more just a question on best practices. Apologies if I went to the wrong venue for help!

Now, I have a whole bunch of relational models, and a few of them are many-to-many with each other. I understand the SqlAlchemy/models side of this, as I've implemented Flask servers with it in the past, and I have an association tables setup. I guess I'm just struggling on how to best manage these relations in `create` and `update`.

I'm unsure as to the best practice for creating or updating schemas in many to many models. Normally with pure SQLAlchemy, I'd just commit the referenced model in a list, but using nested schema classes doesn't seem to work

```
# app/schemas/child.py
from . import parent

...

class ChildUpdate(ChildBase):
    parents: Optional[List[parent.Parent]]
    pass

...
```
But when running tests using the update() function in crud/base.py, the association table does not get populated.

So, it seems the best course of action is to create a new CRUD function to crud_child.py, `add_parent(child: ChildUpdate, parent_id: int)`, and this just takes care of all relational logic in the function to update the models.

So, is the above solution correct (special CRUD function for updating many-to-many, or am I using schemas incorrectly, and `ChildUpdate` should be able to handle this?

Thanks in advance!

**Comment by tiangolo** [comment]
I assume you solved it, thanks for closing the issue :+1:

In any case, I would update each model independently and include only the ID of the related model.

**Comment by sbadisa** [comment]
> Hello, and first off thanks for fastapi, and this bootstrapping project. Have really loved the time I've spent so far re-building my API server in this framework.
> 
> This isn't 100% a fastapi issue, but more just a question on best practices. Apologies if I went to the wrong venue for help!
> 
> Now, I have a whole bunch of relational models, and a few of them are many-to-many with each other. I understand the SqlAlchemy/models side of this, as I've implemented Flask servers with it in the past, and I have an association tables setup. I guess I'm just struggling on how to best manage these relations in `create` and `update`.
> 
> I'm unsure as to the best practice for creating or updating schemas in many to many models. Normally with pure SQLAlchemy, I'd just commit the referenced model in a list, but using nested schema classes doesn't seem to work
> 
> ```
> # app/schemas/child.py
> from . import parent
> 
> ...
> 
> class ChildUpdate(ChildBase):
>     parents: Optional[List[parent.Parent]]
>     pass
> 
> ...
> ```
> 
> But when running tests using the update() function in crud/base.py, the association table does not get populated.
> 
> So, it seems the best course of action is to create a new CRUD function to crud_child.py, `add_parent(child: ChildUpdate, parent_id: int)`, and this just takes care of all relational logic in the function to update the models.
> 
> So, is the above solution correct (special CRUD function for updating many-to-many, or am I using schemas incorrectly, and `ChildUpdate` should be able to handle this?
> 
> Thanks in advance!

I'm also struggling with how to handle many-to-many relationships. Please could you share how you ended up solving this?

Thanks!

**Comment by LarsaSolidor** [comment]
Yes! I too would love to know what the best practice is for creating many to many relationships in Fast API.

**Comment by myfoostrong** [comment]
I'll check back in with what I did later today or tomorrow

**Comment by alexferrari88** [comment]
+1 @myfoostrong

**Comment by apratico** [comment]
+1 @tiangolo

**Comment by myfoostrong** [comment]
Sorry for taking so long to respond! I'm posting what I did here, no promises on whether it's the right way to do it!

So, I had a many-to-many relationship between teams and players.

So the Team model `app/models/team.py` looks like the following:
```
team_player_assoc = Table('team_player_assoc', Base.metadata,
                          Column('team_id', Integer, ForeignKey('team.id')),
                          Column('player_id', Integer, ForeignKey('player.id'))
                          )


class Team(Base):
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    url = Column(String)
    photo_url = Column(String, default="team_default.jpg")
    owner_id = Column(Integer, ForeignKey("user.id"))
    owner = relationship("User", back_populates="teams")
    rosters = relationship("Roster", back_populates="team")
    players = relationship(
        "Player",
        secondary=team_player_assoc,
        backref="teams")

    def can_manage(self, user_id: int):
        return self.owner_id == user_id
```

The schema:
```
# Shared properties
class TeamBase(BaseModel):
    name: Optional[str] = None


# Properties to receive on team creation
class TeamCreate(TeamBase):
    name: str


# Properties to receive on team update
class TeamUpdate(TeamBase):
    pass


# Properties shared by models stored in DB
class TeamInDBBase(TeamBase):
    id: int
    name: str
    owner_id: int

    class Config:
        orm_mode = True


# Properties to return to client
class Team(TeamInDBBase):
    photo_url: str


# Full properties to return to client
class TeamFull(Team):
    players: List[Player]
```

Then in `app/api/api_v1/endpoints/teams.py` I had the following endpoint:
```
@router.post("/{id}/player/{player_id}", response_model=schemas.Msg, status_code=201)
def team_add_player(
    *,
    db: Session = Depends(deps.get_db),
    id: int,
    current_user: models.User = Depends(deps.get_current_active_user),
) -> Any:
    """
    Update an team.
    """
    team = crud.team.get(db=db, id=id)
    player = crud.player.get(db=db, id=player_id)
    if not team:
        raise HTTPException(status_code=404, detail="Team not found")
    if not player:
        raise HTTPException(status_code=404, detail="Player not found")
    if not crud.user.is_superuser(current_user) and not team.can_manage(current_user.id):
        raise HTTPException(status_code=400, detail="Not enough permissions")
    crud.team.add_player(db=db, id=id, player_id=player_id)
    return {"msg": "Player request created"}
```

Then in `app/crud/crud_team.py`
```
def add_player(
            self, db: Session, *, db_obj: Team, player_id: int
    ) -> Team:
        obj_in_data = jsonable_encoder(db_obj)
        player_add = crud.player.get(db, player_id)
        team_players = db_obj.players
        if player_add not in team_players:
            team_players.append(player_add)
            setattr(db_obj, "players", team_players)
            db.add(db_obj)
            db.commit()
            db.refresh(db_obj)
        return db_obj
```

That's the extent of the functionality, and it all works. I had wondered if some of the pydantic/sqlalchemy magic would help out here, but just need to manage it with a separate function. 

Hope it helps!

**Comment by alexandrealfa** [comment]
Thank you @myfoostrong!.

**Comment by dongfengweixiao** [comment]
> Sorry for taking so long to respond! I'm posting what I did here, no promises on whether it's the right way to do it!
> 
> So, I had a many-to-many relationship between teams and players.
> 
> So the Team model looks like the following:`app/models/team.py`
> 
> ```
> team_player_assoc = Table('team_player_assoc', Base.metadata,
>                           Column('team_id', Integer, ForeignKey('team.id')),
>                           Column('player_id', Integer, ForeignKey('player.id'))
>                           )
> 
> 
> class Team(Base):
>     id = Column(Integer, primary_key=True, index=True)
>     name = Column(String, index=True)
>     url = Column(String)
>     photo_url = Column(String, default="team_default.jpg")
>     owner_id = Column(Integer, ForeignKey("user.id"))
>     owner = relationship("User", back_populates="teams")
>     rosters = relationship("Roster", back_populates="team")
>     players = relationship(
>         "Player",
>         secondary=team_player_assoc,
>         backref="teams")
> 
>     def can_manage(self, user_id: int):
>         return self.owner_id == user_id
> ```
> 
> The schema:
> 
> ```
> # Shared properties
> class TeamBase(BaseModel):
>     name: Optional[str] = None
> 
> 
> # Properties to receive on team creation
> class TeamCreate(TeamBase):
>     name: str
> 
> 
> # Properties to receive on team update
> class TeamUpdate(TeamBase):
>     pass
> 
> 
> # Properties shared by models stored in DB
> class TeamInDBBase(TeamBase):
>     id: int
>     name: str
>     owner_id: int
> 
>     class Config:
>         orm_mode = True
> 
> 
> # Properties to return to client
> class Team(TeamInDBBase):
>     photo_url: str
> 
> 
> # Full properties to return to client
> class TeamFull(Team):
>     players: List[Player]
> ```
> 
> Then in I had the following endpoint:`app/api/api_v1/endpoints/teams.py`
> 
> ```
> @router.post("/{id}/player/{player_id}", response_model=schemas.Msg, status_code=201)
> def team_add_player(
>     *,
>     db: Session = Depends(deps.get_db),
>     id: int,
>     current_user: models.User = Depends(deps.get_current_active_user),
> ) -> Any:
>     """
>     Update an team.
>     """
>     team = crud.team.get(db=db, id=id)
>     player = crud.player.get(db=db, id=player_id)
>     if not team:
>         raise HTTPException(status_code=404, detail="Team not found")
>     if not player:
>         raise HTTPException(status_code=404, detail="Player not found")
>     if not crud.user.is_superuser(current_user) and not team.can_manage(current_user.id):
>         raise HTTPException(status_code=400, detail="Not enough permissions")
>     crud.team.add_player(db=db, id=id, player_id=player_id)
>     return {"msg": "Player request created"}
> ```
> 
> Then in `app/crud/crud_team.py`
> 
> ```
> def add_player(
>             self, db: Session, *, db_obj: Team, player_id: int
>     ) -> Team:
>         player_add = crud.player.get(db, player_id)
>         team_players = db_obj.players
>         if player_add not in team_players:
>             team_players.append(player_add)
>             setattr(db_obj, "players", team_players)
>             db.add(db_obj)
>             db.commit()
>             db.refresh(db_obj)
>         return db_obj
> ```
> 
> That's the extent of the functionality, and it all works. I had wondered if some of the pydantic/sqlalchemy magic would help out here, but just need to manage it with a separate function.
> 
> Hope it helps!

The code can be optimized, query player exists in both logical code and crud code.

**Comment by myfoostrong** [comment]
Yeah you're right, thanks!

I guess I didn't want to assume the callee always had the player, before
calling the CRUD function, but probably best to optimize now, and change
later, but only if required.
