### ISSUE TITLE
[BUG] SQLAlchemy Exception when using Enums and jsonable_encoder

### ISSUE THREAD

**Issue by ebreton** [tiangolo/full-stack-fastapi-postgresql#21]
Issue added for reference.

- Full description in appropriate repo: https://github.com/tiangolo/fastapi/issues/196
- Exception thrown: `sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input value for enum YOUR-TYPE: "YOUR-VALUE"`

**Comment by tiangolo** [comment]
Thanks, I'll check it.

**Comment by AnneNamuli** [comment]
I am having almost the same issue.. I keep getting validation errors when i use `enum` type

**Comment by ebreton** [comment]
I am working on it, and got it running with CrudBase. I will update #23 accordingly asap.

I still have one limit though, which is using the same string for name and value.
- value because it is used by pydantic
- name because it is used by SQLalchemy

I keep you posted...

**Comment by AnneNamuli** [comment]
Thanks!!

**Comment by tiangolo** [comment]
I think this was solved in your PR right @ebreton ? :nerd_face: :rocket: 

May we close it?

**Comment by ebreton** [comment]
You are right @tiangolo, thanks for the clean-keeping work. And for the whole fastapi ecosystem. It rocks 🌟 💎
