### ISSUE TITLE
Does fastapi support multiple factor authentication?

### ISSUE THREAD

**Issue by tatdatpham** [tiangolo/full-stack-fastapi-postgresql#210]
Hi everyone, Does fastapi support multiple factor authentication? (using google authenticator app)
I'm try to implement MFA into my project (my project base on full-stack-fastapi-postgresql). 
Thank!

**Comment by ToroNZ** [comment]
Have you considered handling MFA on the front-end? 

IMHO it would be more elegant (though may not fit your use case).

**Comment by SebastianLuebke** [comment]
Of course it does but its up to you to implement it. check out https://pypi.org/project/onetimepass/

**Comment by tiangolo** [comment]
Yep, it's something that you can implement with FastAPI indeed, but you would probably implement it on your own depending on your use case, authentication provider, how you manage users, etc.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
