### ISSUE TITLE
Service 'frontend' failed to build

### ISSUE THREAD

**Issue by cmonprogram** [tiangolo/full-stack-fastapi-postgresql#215]
### Console output:
```
Step 9/13 : RUN npm run build
 ---> Running in e9e69a302e47

> frontend@0.1.0 build /app
> vue-cli-service build


-  Building for production...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit

  `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
  and `regenerator-runtime/runtime` separately
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! frontend@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-11T08_20_29_864Z-debug.log
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 137
```
### Step to reproduce:
cookiecutter https://github.com/tiangolo/full-stack-fastapi-postgresql
docker-compose up -d

### Enviroment:
debian 9.6
docker 19.03.11
docker-composer 1.26.0

### Additional:
`/frontend: npm install && npm build` works fine in native system.
 Build complete. The dist directory is ready to be deployed.

**Comment by mlaradji** [comment]
This part
```
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
```
points to an out of memory problem. How much RAM and free RAM do you have?

**Comment by cmonprogram** [comment]
> This part
> 
> ```
> Killed
> npm ERR! code ELIFECYCLE
> npm ERR! errno 137
> ```
> 
> points to an out of memory problem. How much RAM and free RAM do you have?

```
free -h
              total        used        free      shared  buff/cache   available
Mem:           922M        180M        373M        3.8M        369M        597M
Swap:            0B          0B          0B
```

**Comment by mlaradji** [comment]
@cmonprogram In the npm log, we have the line
```
-  Building for production...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
```
but you only have a maximum of 922MB. I would suggest to either increase the RAM, or add a swapfile (discouraged if your disk is an SSD). There may be better solutions.

**Comment by tiangolo** [comment]
Thanks for the help here @mlaradji ! :clap: :bow: 

If that solves the original problem, then you can close this issue @cmonprogram  :heavy_check_mark:
