### ISSUE TITLE
upgrade path?

### ISSUE THREAD

**Issue by nareto** [tiangolo/full-stack-fastapi-postgresql#216]
Is there any recommended way, or is it possible at all, to upgrade one's local repository with the new releases?

What I mean is: I cloned this repository in January, initialized it with cookiecutter. Since then I've made some changes, mostly added stuff to the database models, crud and api. But the whole architecture has remained the same.

Is there any way for me to incorporate the updates from the master branch?

**Comment by nareto** [comment]
I realized it's probably I'm just not used to do merges with conflicting changes and it's somewhat of a silly question: I can just pull in the changes on a separate branch, change back to mine and do a merge right?

The next question then would be: is it worth it? What kind of updates go in the master branch in this repo?

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
