### ISSUE TITLE
Ignore .env by default

### ISSUE THREAD

**Issue by paxcodes** [tiangolo/full-stack-fastapi-postgresql#218]
Thanks @tiangolo for another awesome tool.

I was wondering if we should add the .env in the .gitignore file by default. 

I understand people have different workflows but I wonder if it would be better that the .env file is _explicity_ exposed if the workflow demands it, instead of needing to explicitly hide the .env file which usually contain secrets.

**Comment by paxcodes** [comment]
Looks like it's been discussed already. I should have searched more closely.

https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/122
https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/128

**Comment by tiangolo** [comment]
Yep, thanks for closing the issue :+1:
