### ISSUE TITLE
Verify password token : key does not exist?

### ISSUE THREAD

**Issue by sheoak** [tiangolo/full-stack-fastapi-postgresql#220]
https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/490c554e23343eec0736b06e59b2108fdd057fdc/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/utils.py#L104

Shouldn't it be "sub" instead of "email"?

**Comment by tiangolo** [comment]
Yep, I think this is fixed here: https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/172

I have to review a lot of PRs and revamp this repo, but first I want to finish things in SQLModel, I made it for this repo. Hopefully soon! 🤞 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
