### ISSUE TITLE
Protected and Public APIs

### ISSUE THREAD

**Issue by kwatog** [tiangolo/full-stack-fastapi-postgresql#225]
Hi! I'm checking out this awesome boilerplate repo. It's all find and working until I added my own endpoints which are meant to be public. I somehow can't find the config to exclude it from authentication. I always get the 'Not authenticated' response. Can anyone point me to the right direction?  I think it's just there but am already splitting my hairs but still couldn't figure it out.

**Comment by kwatog** [comment]
okay. as expected, I made some stupid mistake in the router config when doing include_router.

Sorry for the trouble.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue! :+1:
