### ISSUE TITLE
SERVER_HOST   field required (type=value_error.missing) after running cookiecutter

### ISSUE THREAD

**Issue by rohitkumar93** [tiangolo/full-stack-fastapi-postgresql#228]
I am trying to run this project just on the local to check it out, and I followed the instructions given in the [readme](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/README.md).  I installed poetry with no errors and went to the location backend/app. I try to run the initial_data.py or the init_db.py file to create the tables inside my database, but I get this error:
`SERVER_HOST
  field required (type=value_error.missing)
`
Is there something else I have to run first? I reckon we have to create the tables first by running init_db.py. I am very new to docker, hence I am trying to just run it in the local with the backend and frontend. I supplied the config.py with default values, but cannot find how to give value to this variable 'SERVER_HOST'.

**Comment by tiangolo** [comment]
You probably won't be able to access the DB in Docker Compose from local code, that's why you would get the error.

Try first following the instructions without changes and check if that works first.
