### ISSUE TITLE
can this project easily modified into react frontend?

### ISSUE THREAD

**Issue by EtherLoda** [tiangolo/full-stack-fastapi-postgresql#233]
React is my main frontend skill stack, and dont want to turn to vue now.

**Comment by Biskit1943** [comment]
Hey, as stated in the [README.md](https://github.com/tiangolo/full-stack-fastapi-postgresql/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D#removing-the-frontend) you can easily remove the frontend. But you will then have to create the frontend stuff yourself.

I did find a similar [template](https://github.com/Buuntu/fastapi-react) where fastAPI and React were used together.

**Comment by ChenJanson** [comment]
> Hey, as stated in the [README.md](https://github.com/tiangolo/full-stack-fastapi-postgresql/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D#removing-the-frontend) you can easily remove the frontend. But you will then have to create the frontend stuff yourself.
> 
> I did find a similar [template](https://github.com/Buuntu/fastapi-react) where fastAPI and React were used together.

Thanks, I like your thing. And I have stared your project.

**Comment by wolfieorama** [comment]
Thanks this is a dope project

**Comment by tiangolo** [comment]
Yep, it should be quite doable. In fact, I've been wanting to refactor it to use React. I have to update a lot of things in this project but first I want to finish with SQLModel to include it here. 🤓
