### ISSUE TITLE
Question: How to run tests outside of a docker container?

### ISSUE THREAD

**Issue by omrihar** [tiangolo/full-stack-fastapi-postgresql#24]
Hi, thanks for the beautiful framework and cookiecutter project!

I'm setting up a project using this cookiecutter and I haven't managed to run the tests without the use of the script that generates the tests docker container. Is there a way to quickly run the tests without recreating a docker container? 
I plan to use TDD in my development and if I have to wait a long time for the tests to run it will discourage me from following that practice... 

I tried running the tests by executing `docker-compose exec backend bash` and then running the tests running `bash tests-start.sh` and also by simply running `pytest`, but for the former the tests don't manage to authenticate and for the latte I get a `pytest` not found error.

Any hints would be very welcome!

**Comment by ebreton** [comment]
Hi @omrihar 

You can check https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/12 where I explain how to do exactly what you are looking for, and also another way (more elegant) to do it as suggested by @tiangolo 

To even make his proposition better, there is https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/17 which has been merged in

**Comment by omrihar** [comment]
Hi @ebreton 
Thanks for your reply! I also got an answer from @tiangolo on gitter for this. The tests (of the cookiecutter project) still take about 6-8 seconds to run, which is not negligible, but seems much better than what I thought at first (which was that you should use the script that creates the docker images from scratch). I also managed to install `pytest-watch` inside the container and use `ptw` to continuously run the tests whenever the code changes :)

btw, I really like your suggestion for the `CrudBase` in the (still open) PR.

Cheers,
Omri

**Comment by tiangolo** [comment]
Thanks for your help @ebreton !

I'm glad you solved it @omrihar .
