### ISSUE TITLE
Admin Dashboard for this stack

### ISSUE THREAD

**Issue by pg1671** [tiangolo/full-stack-fastapi-postgresql#247]
Hi, I am looking at using this stack for a new project. I have used Django in the past and one of the most useful aspects is the automatic admin dashboard.

Are their recommended admin dashboards for this stack or suggested options?

**Comment by tiangolo** [comment]
I don't currently have one, I haven't used one myself, but that is normally coupled with the database and ORM, so you might probably try to find an admin dashboard for SQLAlchemy.

I built SQLModel to integrate it with this project, but I haven't had the time to finish it. But that's the plan. And I know there are already admin UIs for SQLModel too.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
