### ISSUE TITLE
backend does not start, even after changing line endings from CRLF to LF manually

### ISSUE THREAD

**Issue by pranjalsrv** [tiangolo/full-stack-fastapi-postgresql#248]
This is in the output of command `docker-compose logs`:

```backend_1  | Checking for script in /app/prestart.sh
backend_1  | There is no script /app/prestart.sh
backend_1  | INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
backend_1  | INFO:     Started reloader process [1] using statreload
backend_1  | ERROR:    Error loading ASGI app. Import string ":app" must be in format "<module>:<attribute>".
```

This issue still persists on running on Windows. It is the duplicate of closed issue #90, merged by PR #149 
I tried changing the line endings using both VSCode and manually using the command:`find . -type f -exec dos2unix {} \;`, but the issue still exists. So the closed issue in #13 is not working as well.

I am able to create a bash session in the backend container:

```
> docker-compose exec backend bash
WARNING: Some services (backend, db, pgadmin, proxy) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
root@7bf80e8eb31a:/app#
```

I can access the Traefik and pgAdmin endpoints, but can't login using the API, or use the API endpoints.

**Comment by tiangolo** [comment]
A recent update of this project generator modifies the files after the project generation to replace those newline characters. Do you still have issues with a freshly generated project?
