### ISSUE TITLE
Type error when implementing additional responses

### ISSUE THREAD

**Issue by ryanditjia** [tiangolo/full-stack-fastapi-postgresql#252]
Following the example from [the additional responses guide](https://fastapi.tiangolo.com/advanced/additional-responses/#combine-predefined-responses-and-custom-ones):

```py
class Message(BaseModel):
    message: str


responses = {
    401: {"model": Message}
}


@router.put("/me/password", responses=responses, status_code=status.HTTP_204_NO_CONTENT)
```

I’m getting this mypy error on `responses` argument:

> Argument "responses" to "put" of "APIRouter" has incompatible type "Dict[int, Dict[str, Type[Message]]]"; expected "Optional[Dict[Union[int, str], Dict[str, Any]]]"

When I change the argument to `responses={**responses}`, the error is still there, albeit a little bit different:

> List item 0 has incompatible type "Dict[int, Dict[str, Type[Message]]]"; expected "Mapping[Union[int, str], Dict[str, Any]]"

Does anyone know why this is happening?

**Comment by vrodochenko** [comment]
I would assume that mypy cannot derive the type of your dictionary the way you want it to, which leads to this obscure error. Consider adding an annotation:

```python
from typing import Dict

responses: Dict = {
    401: {"model": Message}
}
```
to make things pass the validation.

Also you can go through mypy issues (e.g [this one](https://github.com/python/mypy/issues/5382)) to learn more.

**Comment by ryanditjia** [comment]
Thanks so much, your answer worked.
