### ISSUE TITLE
question: Postgres default user/pass?

### ISSUE THREAD

**Issue by iAnanich** [tiangolo/full-stack-fastapi-postgresql#255]
It seems that this setup does not modify the default root username and password, leaving them `postgres:postgres`. Is it considered safe enough?

**Comment by SebastianLuebke** [comment]
The database container is not reachable from external networks so it is safe.

**Comment by tiangolo** [comment]
Yep, exactly what @SebastianLuebke says ☝️ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
