### ISSUE TITLE
qustion: purpose if build-stag/prod separation?

### ISSUE THREAD

**Issue by iAnanich** [tiangolo/full-stack-fastapi-postgresql#256]
For the container image, the only difference is in domain for staging/production, but domain is stored as an environment variable so it can be set/overridden later on `deploy` stage.

**Comment by ryanditjia** [comment]
I assume that’s because frontend needs to hardcode the DOMAIN at build time.

**Comment by tiangolo** [comment]
Yep, as @ryanditjia says. :point_up:
