### ISSUE TITLE
[BUG] Pydantic exception when using JSON fields in postreSQL

### ISSUE THREAD

**Issue by ebreton** [tiangolo/full-stack-fastapi-postgresql#26]
Issue added for reference.

- The issue comes from the serialization of the SQL objects by fastapi.
- detailed in https://github.com/tiangolo/fastapi/issues/211

**Comment by tiangolo** [comment]
Check out the answer here: https://github.com/tiangolo/fastapi/issues/211#issuecomment-491506412

**Comment by ebreton** [comment]
The solution from @tiangolo consists of simply using `Union[dict, list, set, float, int, str, bytes, bool]` to get some python objects instead of `Json` which simply returns a valid JSON string.

Details in the linked issue on fastapi 🔗 

Thanks @tiangolo  !

**Comment by tiangolo** [comment]
Great! Thanks for coming back and closing the issue.
