### ISSUE TITLE
Bug: Unable to update username at the frontend because no `password` is posted 

### ISSUE THREAD

**Issue by mgao6767** [tiangolo/full-stack-fastapi-postgresql#260]
Hi tiangolo, thanks a lot for this amazing template! There's a bug I found that prevents updating username at the frontend.

The following line of code in CRUDUser needs the presence of `password` in the post body. However, line 33 excludes the unset. The form data doesn't contain `password` since it's originated from updating user profile, leading to a runtime error.

https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/490c554e23343eec0736b06e59b2108fdd057fdc/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/crud/crud_user.py#L27-L38

**Comment by mgao6767** [comment]
Closed as this has been noticed here: https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/249#issuecomment-686565378

**Comment by teschmitt** [comment]
The solution in the referenced issue didn't solve this issue for me. A more trivial solution is to to replace the following line in  `backend > app > app > crud > crud_user.py`

```python
if update_data["password"]:
```

with

```python
if update_data.get("password", False):
```

until this has been fixed in a future release.
