### ISSUE TITLE
Deploy staging

### ISSUE THREAD

**Issue by fsanne** [tiangolo/full-stack-fastapi-postgresql#265]
Not really an issue, but I'm not sure which variables to change to deploy a separate swarm staging stack. No matter which envs I edit it seems to tag it as prod regardless. Got a prod stack running in the swarm already and would like to get staging up and running. In hindsight I should have done staging first I guess, since it won't be in production yet. Kinda new at this and got the swarm and stack running after two days of using docker, so might be more stupid questions in the future!

**Comment by danieljfarrell** [comment]
I did this yesterday!

Answer is in the [project README](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/README.md#deploy-to-a-docker-swarm-mode-cluster) and by hunting around the [github-ci.yml](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.gitlab-ci.yml)

Let's pretend I own the domain _example.com_.

First thing is to add A/AAAA records for,

 * stag.example.com
 * www.stag.example.com
 * example.com
 * www.example.com

to point them to at least one IP in your swarm. If you forget to add the `www.*` records Let's Encrypt certificate will be invalid.

# Staging

Run the build script on all nodes in your swarm (if you are not using image repository),

    TAG=stag FRONTEND_ENV=staging sh ./scripts/build.sh

Return to a leader node and run the build script,

    DOMAIN=stag.example.com \
    TRAEFIK_TAG=stag-example-com \
    STACK_NAME=stag-example-com \
    TAG=stag \
    bash ./scripts/deploy.sh

# Production

Production is much the same. Just change the environmental variables

    TAG=prod FRONTEND_ENV=production sh ./scripts/build.sh

Again, do the above all nodes in the swarm.

Now run the deploy script after updating the variables,

    DOMAIN=example.com \
    TRAEFIK_TAG=prod-example-com \
    STACK_NAME=prod-example-com \
    TAG=prod \
    bash ./scripts/deploy.sh

**Comment by fsanne** [comment]
Thanks a bunch man, great explanation! I think I actually got it working by chance, probably altered a few variables I didn't really need to in the process but conf backup is always a good thing.

**Comment by danieljfarrell** [comment]
Cool, you should probably close the issue.

**Comment by tiangolo** [comment]
Thanks a lot for the help @danieljfarrell ! 🍰 

And thanks for coming back to close the issue @fsanne ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
