### ISSUE TITLE
creds are due

### ISSUE THREAD

**Issue by haviduck** [tiangolo/full-stack-fastapi-postgresql#267]
hey, no issue or anything. Just wanted to throw out a big thank you for providing such an excellent stack. ive learned alot deploying it and after alot of hours ive successfully turned it into an autoscalable yolo4 videoinferencing api.

ive learned vue, vuex, a whole lot about swarm and traefik and im Just thrilled. 

fastapi is Just amazing.

**Comment by tiangolo** [comment]
Thanks a lot for the kind words! It's very uncommon to stumble on an issue with a message as nice as this one, thanks for taking the time to write it!

I have a lot to update in this project, but I'm glad it has been useful! 🎉 

I'll close it now, but thanks again! ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
