### ISSUE TITLE
docker-compose ERROR

### ISSUE THREAD

**Issue by littleforce163** [tiangolo/full-stack-fastapi-postgresql#270]
ERROR: no such image: {{cookiecutter.docker_image_frontend}}:latest: invalid reference format

**Comment by SebastianLuebke** [comment]
I think you cloned the repo instead of using cookiecutter to create your own project.
```console
pip install cookiecutter
cookiecutter https://github.com/tiangolo/full-stack-fastapi-postgresql
```

**Comment by tiangolo** [comment]
Thanks @SebastianLuebke!

@littleforce163 If the original problem is solved, then you can close this issue :heavy_check_mark:
