### ISSUE TITLE
How to run a background task every X seconds

### ISSUE THREAD

**Issue by Biskit1943** [tiangolo/full-stack-fastapi-postgresql#274]
Hey, I'm in need of a task, which is run every 24h/86400s. As this template does not make use of async how would I implement such a task?

My current idea would be to spawn a thread in the `main.py` which does nothing more than a `sleep` and the wanted background task. 

Please correct me if there is a better solution to this or if there are any other options.

**Comment by haviduck** [comment]
id recommend using celeryworkers for this

[periodic tasks](https://docs.celeryproject.org/en/stable/userguide/periodic-tasks.html)

**Comment by Biskit1943** [comment]
Thanks @haviduck this seems to be the correct way for this project. For anyone who wants to quickly do this, here is my solution:

in `backend/app/app/core/celery_app.py` I added a new task_route:
```python
celery_app.conf.task_routes = {
    "app.worker.test_celery": "main-queue",
    "app.worker.scheduled_task": "main-queue"
}
```

In `/backend/app/app/worker.py` I added the corresponding `scheduled_task` function together with the registration to the beat:
```python
@celery_app.task
def scheduled_task() -> str:
    print("I'm doing my part!")
    return "done"


# Configure celery beat
@celery_app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    sender.add_periodic_task(10.0, scheduled_task.s(), name='Do something every 10 seconds')
```

And finally I added `--beat` to the worker in `backend/app/worker-start.sh`. However, this isn't the correct way corresponding to the docs:

```
Note:
-B is meant to be used for development purposes. For production environment, you need to start celery beat separately.
```

But I only have one worker, so this is alright.

**Comment by tiangolo** [comment]
Thanks for the help @haviduck! 🍰 

And thanks for reporting back and closing the issue @Biskit1943 ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
