### ISSUE TITLE
Move Frontend to Subdomain

### ISSUE THREAD

**Issue by dhruv4** [tiangolo/full-stack-fastapi-postgresql#277]
Hey there! I am new to Docker and Traefik, so thanks for bearing with me. Is it possible to move the frontend application to a subdomain rather than the main domain when deploying with Docker Swarm to an AWS EC2? Where would that be defined?

Thanks!

**Comment by Biskit1943** [comment]
Look at the docker-compse.yml

Specifically the frontend service:
https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/490c554e23343eec0736b06e59b2108fdd057fdc/%7B%7Bcookiecutter.project_slug%7D%7D/docker-compose.yml#L181-L192

Currently the rule is to route to `/`, what you want is `Host(`<frontend>.${DOMAIN?Variable not set}`)` where `<frontend>` would be your subdomain. 

And when you're at it, you might also want to change the api routing here:
https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/490c554e23343eec0736b06e59b2108fdd057fdc/%7B%7Bcookiecutter.project_slug%7D%7D/docker-compose.yml#L140-L161

You then need to configure your frontend to use this new domain:
https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/490c554e23343eec0736b06e59b2108fdd057fdc/%7B%7Bcookiecutter.project_slug%7D%7D/frontend/.env#L1-L10

For reference look here: https://docs.traefik.io/routing/providers/docker/

I don't have any knowledge on AWS and therefore I can't help you there.

**Comment by dhruv4** [comment]
Thanks so much!! I'll try this out and reopen if it doesn't work in production.

**Comment by tiangolo** [comment]
Thanks for the help @Biskit1943! 🚀 

And thanks for coming back to close the issue @dhruv4 ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
