### ISSUE TITLE
How does backend start?

### ISSUE THREAD

**Issue by orihomie** [tiangolo/full-stack-fastapi-postgresql#279]
I'd like to know how does backend start in container, for now I see one starting point and its **prestart.sh** but where is start itself?
FastApi guides tells that it should be started by 
> uvicorn < module >:< app >

and I cannot find that anywhere 😒 

I'd like to see all triggers/ scripts chained one after other to make clear how does all things work here

**Comment by Biskit1943** [comment]
If you look into the Dockerfile of the backend:

https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/490c554e23343eec0736b06e59b2108fdd057fdc/%7B%7Bcookiecutter.project_slug%7D%7D/backend/backend.dockerfile#L1

It pulls this https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi container. If you scroll down to `How to use` you'll see this:

```
It will expect a file at /app/app/main.py.

Or otherwise a file at /app/main.py.
```

If you want to dig deeper, you should look into the code of that container.

**Comment by orihomie** [comment]
As we can see here
https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/docker-images/python3.7.dockerfile
**start.sh** is here
https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/docker-images/start.sh
It's exactly what I was searching for to clarify for myself all magic that forces app to rise & shine, thanks for the aiming.

**Comment by tiangolo** [comment]
Thanks for the help @Biskit1943! 🚀 

And thanks for coming back to close the issue @orihomie ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
