### ISSUE TITLE
available in serverless environment?

### ISSUE THREAD

**Issue by adsee42** [tiangolo/full-stack-fastapi-postgresql#283]
I'm currently building an app using node.js running on Google Cloud Run, which is serverless, and considering changing to python. 
FastAPI seems a good choice, and this boilerplate looks great!

To deploy the backend part (will be replacement of my node.js server) of this boilerplate as a serverless service, is there anything to pay attention to?

Any advice pointing me some direction would be very helpful before I work hard on this.

**Comment by Biskit1943** [comment]
Have a look at the [README](https://github.com/tiangolo/full-stack-fastapi-postgresql/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D) where nearly everything is explained, especially at [this section](https://github.com/tiangolo/full-stack-fastapi-postgresql/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D#removing-the-frontend).

**Comment by tiangolo** [comment]
Thanks for the help @Biskit1943! 🙇 

If that solves your question @adsee42 you can close the issue.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
