### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by littlefixit** [tiangolo/full-stack-fastapi-postgresql#292]
After variables to the cookiecutter script, I get the following: 
```
File "/tmp/tmpxElTBP.py", line 4
    path: Path
        ^
SyntaxError: invalid syntax
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

When I `cat /tmp/tmpxElTBP.py`:
```
from pathlib import Path
path: Path
for path in Path(".").glob("**/*.sh"):
    data = path.read_bytes()
    lf_data = data.replace(b"\r\n", b"\n")
    path.write_bytes(lf_data)

```
I'm uncertain what the issue is, and could use some guidance.

**Comment by carlosparedes** [comment]
You are running cookiecutter in python 2.7 environment. Create python 3 virtual environment and run cookiecutter again, don't forget to pip install wheel before installing cookiecutter!

**Comment by jwhit265** [comment]
I also got the same error and also was not running python 3. I am now using python 3 in a virtual environment but am getting the same error.

**Comment by Mause** [comment]
You are probably using too old a version of python 3

**Comment by tiangolo** [comment]
Thanks for the help here everyone! 👏  🙇 

If that solves the original problem, then you can close this issue ✔️

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
