### ISSUE TITLE
Can't run the Celery Beat Scheduler

### ISSUE THREAD

**Issue by jceyrac** [tiangolo/full-stack-fastapi-postgresql#293]
Hi!
I need to schedule a repetitive task that would do some work and save it in the DB.
For this matter I'm trying to implement the solution using Celery and workers shared by @Biskit1943 [here](https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/274#issuecomment-696556450) but I can't manage to run the beat scheduler at the initialisation of the Celery with the command `--beat` in `app/worket-start.sh`:
`celery -A app.worker worker --beat -l info -Q main-queue -c 1`

From what I understand if the scheduler is correctly called, I should see something similar to:
```
2017–10–22 23:47:28,861: INFO/MainProcess] beat: Starting…
[2017–10–22 23:48:00,019: INFO/MainProcess] Scheduler: Sending due task test-celery (app.tasks.test.print_hello)
```

But on my side there is nothing in the logs after the initialisation of Celery:
```
[2020-10-14 15:31:02,182: INFO/MainProcess] Connected to amqp://guest:**@queue:5672//
[2020-10-14 15:31:02,201: INFO/MainProcess] mingle: searching for neighbors
[2020-10-14 15:31:03,233: INFO/MainProcess] mingle: all alone
[2020-10-14 15:31:03,253: INFO/MainProcess] celery@719f319c1efd ready.
[2020-10-14 15:31:04,155: INFO/MainProcess] Events of group {task} enabled by remote.
```

Celery seems to be working fine though since I can run the worker test_celery defined in `app/worker` with the input str `test`and get this answer:
```
[2020-10-14 15:31:03,233: INFO/MainProcess] mingle: all alone
[2020-10-14 15:31:03,253: INFO/MainProcess] celery@719f319c1efd ready.
[2020-10-14 15:31:04,155: INFO/MainProcess] Events of group {task} enabled by remote.
[2020-10-14 15:42:36,491: INFO/MainProcess] Received task: app.worker.test_celery[f66fc2a2-225d-4200-a61e-3e9972aa61a0]
/usr/local/lib/python3.7/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is absolutely not recommended!
Please specify a different user using the --uid option.
User information: uid=0 euid=0 gid=0 egid=0
uid=uid, euid=euid, gid=gid, egid=egid,
[2020-10-14 15:42:36,551: INFO/ForkPoolWorker-1] Task app.worker.test_celery[f66fc2a2-225d-4200-a61e-3e9972aa61a0] succeeded in 0.01056517699998949s: 'test task return test'
```

Could this be related to a refresh issue of the docker instance that doesn't take into account the new parameter --beat? In fact, I can still run the test_celery worker after restart even after commenting the celery launch commands:

-  `celery -A app.worker worker -l info -Q main-queue -c 1` in `app/worker-start.sh`
-  `RUN=celery -A app.worker worker -l info -Q main-queue -c 1` in `docker-compose.override.yml`

Any help would be much appreciated!

**Comment by Biskit1943** [comment]
Did you add the task to the task_routes, in `backend/app/app/core/celery_app.py`?
Because if you did not apply it to a route it can't be called and does not report any errors.

**Comment by jceyrac** [comment]
> Did you add the task to the task_routes, in `backend/app/app/core/celery_app.py`?

Thanks for your quick reply @Biskit1943! Yes, in celery_app.py I have:
```python
from celery import Celery

celery_app = Celery("worker", broker="amqp://guest@queue//")

celery_app.conf.task_routes = {
    "app.worker.test_celery": "main-queue",
    "app.worker.scheduled_task": "main-queue"
}
```
And in worker.py:
```python
@celery_app.task
def scheduled_task() -> str:
    print("*******I'm doing my part!*******")
    return "done"

# Configure celery beat
@celery_app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    sender.add_periodic_task(10.0, scheduled_task.s(), name='Do something every 10 seconds')
``` 

Is it normal that if I comment the line `celery worker -A app.worker -l info  -Q main-queue -c 1` in `backend/app/worker-start.sh' celery is still launched at startup? Maybe an older version of the file is used and not refreshed?

**Comment by jceyrac** [comment]
After a deleting all the volumes and images and rebuilding  everything again with docker-compose up -d, it works now! 
```
[2020-10-14 21:10:40,817: INFO/Beat] Scheduler: Sending due task Do something every 10 seconds (app.worker.scheduled_task)
[2020-10-14 21:10:40,823: INFO/MainProcess] Received task: app.worker.scheduled_task[25a0d033-ff5c-4a63-839f-0fd3355b932f]
[2020-10-14 21:10:40,825: WARNING/ForkPoolWorker-2] *******I'm doing my part!*******
[2020-10-14 21:10:40,826: INFO/ForkPoolWorker-2] Task app.worker.scheduled_task[25a0d033-ff5c-4a63-839f-0fd3355b932f] succeeded in 0.0008159999997587875s: 'done'
```
Is it normal that a change to the worker-start.sh is not automatically taken into account by the docker instance?

**Comment by Biskit1943** [comment]
> After a deleting all the volumes and images and rebuilding everything again with docker-compose up -d, it works now!
> 
> ```
> [2020-10-14 21:10:40,817: INFO/Beat] Scheduler: Sending due task Do something every 10 seconds (app.worker.scheduled_task)
> [2020-10-14 21:10:40,823: INFO/MainProcess] Received task: app.worker.scheduled_task[25a0d033-ff5c-4a63-839f-0fd3355b932f]
> [2020-10-14 21:10:40,825: WARNING/ForkPoolWorker-2] *******I'm doing my part!*******
> [2020-10-14 21:10:40,826: INFO/ForkPoolWorker-2] Task app.worker.scheduled_task[25a0d033-ff5c-4a63-839f-0fd3355b932f] succeeded in 0.0008159999997587875s: 'done'
> ```
> 
> Is it normal that a change to the worker-start.sh is not automatically taken into account by the docker instance?

I don't think this is normal, but I experience this a lot. If I want to make sure my container is built with ALL the data, I usually run build with `--no-cache` which will ignore all old layers and build everything from the ground up.

**Comment by jceyrac** [comment]
I'll try that! Where do you add the --no-cache option?

In the scripts/build.sh file?
```shell
#! /usr/bin/env sh

# Exit in case of error
set -e

TAG=${TAG?Variable not set} \
FRONTEND_ENV=${FRONTEND_ENV-production} \
docker-compose \
-f docker-compose.yml \
build
```
I replace here the line add `build` with `--no-cache`?

**Comment by Biskit1943** [comment]
As said in the answer, `$@` will hold all variables.
I replaced `build` with `build $@` to be able to call the build script with additional options if needed. I don't always want to build with `--no-chache` and if I do want, I can just call it with that as a parameter.

Where it is called? I'm not quite sure what you mean by that. But when you doing local development you just call `docker-compose build --no-cache` but for stag and prod you do as described in the Readme and can than optionally pass the options. For example in the gitlab-ci.yml

Hope I could help.

**Comment by jceyrac** [comment]
Yes, thanks for your help @Biskit1943, everything is clearer now!

**Comment by tiangolo** [comment]
Thanks for the help @Biskit1943! 🍰 

And thanks for coming back to close the issue @jceyrac ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
