### ISSUE TITLE
Flower container not starting because of error: ImportError: cannot import name 'Command' from 'celery.bin.base' 

### ISSUE THREAD

**Issue by jceyrac** [tiangolo/full-stack-fastapi-postgresql#294]
Hi!

I deleted all the volumes and images and rebuilt the projet from scratch using the `docker-compose up -d` command and now the Flower container wouldn't start because of an import error:

 ```
File "/usr/local/bin/flower", line 5, in <module>
from flower.__main__ import main
File "/usr/local/lib/python3.9/site-packages/flower/__main__.py", line 4, in <module>
from flower.command import FlowerCommand
File "/usr/local/lib/python3.9/site-packages/flower/command.py", line 17, in <module>
from celery.bin.base import Command
ImportError: cannot import name 'Command' from 'celery.bin.base' (/usr/local/lib/python3.9/site-packages/celery/bin/base.py)
```
It seems that the installation script is installing celery version 4.4.7 with the latest version of flower. Is this a compatibility issue? If yes, to fix this shall I downgrade the version of  celery? How can i do that?

Thanks a lot for your help!!

**Comment by haviduck** [comment]
yeah, flower is always a bit behind.
in your compose file change to something like:

mher/flower:0.9.4

for the flower service.

**Comment by jceyrac** [comment]
yes, it's working now. Thanks @haviduck !

**Comment by tiangolo** [comment]
Thanks for the help @haviduck! ☕ 

And thanks for coming back to close the issue @jceyrac 🍰 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
