### ISSUE TITLE
[Question] Unable to load celery application because module was not found.

### ISSUE THREAD

**Issue by jceyrac** [tiangolo/full-stack-fastapi-postgresql#295]
Hi,

I created a new celery worker where I would like to use the package BeautifulSoup.
To do so I:
- imported the library `from bs4 import BeautifulSoup` in app/worker.py and used the library in a worker to scrap some data
- added the install command in the `celeryworker.dockerfile` according to the instructions in REAME.md ("If you need to install any additional package to the worker, add it to the file `./backend/app/celeryworker.dockerfile`.": 
```dockerfile
# Install beautifulsoup
ARG INSTALL_BEAUTIFULSOUP=false
RUN bash -c "if [ $INSTALL_BEAUTIFULSOUP == 'true' ] ; then pip install beautifulsoup4 ; fi" 
```
- removed all the containers and images and rebuilt everything with `docker-compose up -d`

But unfortunately the celery container wouldn't start because of the error:
```bash
Error:
Unable to load celery application.
The module bs4 was not found.    
```
Is there something I'm missing to have this new package recognised?

Thanks a lot for any help given!

**Comment by Biskit1943** [comment]
I'm not quite sure, but I don't think that it's Python packages with are meant here... The dockerfile installs all requirements from you pyproject.toml and therefore adding it there should solve this problem. If you install a package with pip to the container, you've installed it to the system not the venv which is created by poetry.

**Comment by Biskit1943** [comment]
BTW, if you have lots of questions @jcaguirre89 maybe ask them in [Gitter](https://gitter.im/tiangolo/fastapi)

**Comment by jceyrac** [comment]
Thanks for your help @Biskit1943, I'll check the pyproject.toml in the container. And post my future questions in Gitter!

**Comment by jceyrac** [comment]
Updating ./backend/app/pyproject.toml with the dependency `beautifulsoup4 = "4.9.3"` and rebuilding the project solved my issue.

**Comment by tiangolo** [comment]
Thanks for the help here @Biskit1943! 🍰 

And thanks for coming back to close the issue @jceyrac ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
