### ISSUE TITLE
Can you explain the resoning behind the api versioning approach?

### ISSUE THREAD

**Issue by danielporto** [tiangolo/full-stack-fastapi-postgresql#299]
Almost every tutorial I've read seem to not like the URI versioning approach for various reasons. Popular examples are found in https://restfulapi.net/versioning/, https://www.youtube.com/watch?v=P0a7PwRNLVU

Without criticizing the approach taken, what is the workflow you have in mind on how to evolve the API, let's say, if there will be ever a version 2, or if one decide to break the API into two parts (one private other public for partners) and how does that changes things like routing/reverse proxy configurations.

The reason I'm asking is that I plan to migrate a current from one implementation to one in FastAPI, but I also wish to keep things running, therefore I would like to keep both APIs, disabling and deprecating things on the old one once is completely ported to the fastapi impl. Thus I stumble upon the problem of versioning  rest apis..

**Comment by haviduck** [comment]
checked This out?
https://pypi.org/project/fastapi-versioning/

**Comment by danielporto** [comment]
Thank you.

**Comment by tiangolo** [comment]
Thanks for the help @haviduck! 🍰 

Thanks for coming back to close the issue @danielporto ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
