### ISSUE TITLE
Accessing wrong key in token verification util on password reset route

### ISSUE THREAD

**Issue by rkrn** [tiangolo/full-stack-fastapi-postgresql#304]
Think you meant to `decoded_token['sub']`?

https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/490c554e23343eec0736b06e59b2108fdd057fdc/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/utils.py#L104

**Comment by kurtrottmann** [comment]
Yes, and a pull request already exists: https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/172

**Comment by rkrn** [comment]
Sweet thanks, closing this.

**Comment by tiangolo** [comment]
Thanks for the help @kurtrottmann! 🚀 

Thanks for closing this one @rkrn ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
