### ISSUE TITLE
local test

### ISSUE THREAD

**Issue by BiswajitBiswa** [tiangolo/full-stack-fastapi-postgresql#313]
when i run the test using
`docker-compose exec backend /app/tests-start.sh`
i get this error 
`OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/app/tests-start.sh\": permission denied": unknown`
i tried even in root directory.

my directory structure is like:
**SETUP-**
backend                    
docker-compose.yml
 README.md
cookiecutter-config-file.yml 
docker-stack.yml
 scripts
docker-compose.override.yml  
frontend

And I am running the script in SETUP directory.

**Comment by haviduck** [comment]
try exec bash or exec sh /app/tests-start.sh . if that doesnt work, go -u root?

**Comment by BiswajitBiswa** [comment]
Thanks it was a root issue.Now its working

**Comment by tiangolo** [comment]
Thanks for the help here @haviduck ! :clap: :bow: 

Thanks for reporting back and closing the issue @BiswajitBiswa  :+1:

**Comment by mklaber** [comment]
If anyone else comes across this issue, on macOS, `-u root` didn't work for me but... making sure that the local file had execute permissions did: `chmod +x backend/scripts/tests-start.sh`
