### ISSUE TITLE
SQLAlchemy 1.4 and asyncio

### ISSUE THREAD

**Issue by arktea** [tiangolo/full-stack-fastapi-postgresql#315]
As mentioned in the coming SQLAlchemy 1.4 [release note](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#asynchronous-io-support-for-core-and-orm), there will be asyncio based connection and session.

Are there plans to switch to async endpoints ?

**Comment by sandys** [comment]
Sqlalchemy 1.4 was released - https://www.sqlalchemy.org/blog/2021/03/15/sqlalchemy-1.4.0-released/

**Comment by conradogarciaberrotaran** [comment]
bump on this. @tiangolo is there something we can contribute to get this feature?

thanks

**Comment by jianyuan** [comment]
I managed to upgrade to SQLAlchemy 1.4 and convert endpoints to asyncio in https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/359. Unfortunately, I couldn't get Celery to work nicely with asyncio yet.

**Comment by sandys** [comment]
hi guys,
I want to contribute my gist here -
https://gist.github.com/sandys/671b8b86ba913e6436d4cb22d04b135f

This is fastapi with python  dataclasses - used to create both sqlalchemy
and pydantic models simultaneously (there is no double definition of
models). I have added a bunch of examples including indexes, mixins, etc
etc
In addition - i have both sync and asyncpg examples (using the new
sqlalchemy async support). Would love comments.
When I benchmarked using locust, I get 400 rps using the gunicorn
commandline in the gist.

**Comment by MrCapsLock** [comment]
Hi, any news about this thread? I'm struggling with async engine and still there are problems that I can't figure them out.

**Comment by AlexanderPodorov** [comment]
@jianyuan , I had the same problem. I'm using the following solution:
```python

def coroutine(function: Callable):
    @wraps(function)
    def wrapper(*args, **kwargs):
        asyncio.run(function(*args, **kwargs))

    return wrapper

@celery.task
@coroutine
async def execute_task():
    # the task code here
```
I'm using the same decorator for `typer` too:

```python
@cli.command()
@coroutine
async def some_func(
    opt1: str = Option(...),
    opt2: str = Option(...)
):
   # your code here
```
It adds additional overhead of course, but it's not critical for my setup. It's nice I can use `AsyncEngine` and `AsyncSession` everywhere in the code.

**Comment by tiangolo** [comment]
Thanks all! The project now uses SQLModel, which is based on SQLAlchemy 2.0. :tada: 

The idea is to keep the project simple and easy to extend and update, so, by default, functions are regular, not `async`, but you can use `async` in your own code bases for the cases where it makes sense, making sure all the internal code is compatible.

SQLModel, as is based on SQLAlchemy 2.0, already supports async too (although it's not properly documented yet). But you can already use it. :nerd_face:
