### ISSUE TITLE
password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by orfevre2013** [tiangolo/full-stack-fastapi-postgresql#316]
Hello, I'm a newbie in FastAPI. I'm on mac with docker for mac.
When I make docker-compose up -d I got the following errors :

`2020-11-15 10:08:49.179 UTC [593] FATAL:  password authentication failed for user "postgres"
backend_1       |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
celeryworker_1  | (Background on this error at: http://sqlalche.me/e/13/e3q8)
db_1            | 2020-11-15 10:08:49.179 UTC [593] DETAIL:  Password does not match for user "postgres".`

Can someone tell what I'am doing wrong?
Thanks you.

**Comment by orfevre2013** [comment]
This issue was already documented [here](https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/176), to fix it choose a 23 length password.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
