### ISSUE TITLE
Alembic: No module named 'app'

### ISSUE THREAD

**Issue by Fingel** [tiangolo/full-stack-fastapi-postgresql#324]
With a fresh clone of this project from cookiecutter, alembic does not run:

```
$ alembic upgrade head
Traceback (most recent call last):
  File "/Users/austin/.virtualenvs/ccfast/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/Users/austin/.virtualenvs/ccfast/lib/python3.9/site-packages/alembic/config.py", line 581, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/austin/.virtualenvs/ccfast/lib/python3.9/site-packages/alembic/config.py", line 575, in main
    self.run_cmd(cfg, options)
  File "/Users/austin/.virtualenvs/ccfast/lib/python3.9/site-packages/alembic/config.py", line 552, in run_cmd
    fn(
  File "/Users/austin/.virtualenvs/ccfast/lib/python3.9/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/Users/austin/.virtualenvs/ccfast/lib/python3.9/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/austin/.virtualenvs/ccfast/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/austin/.virtualenvs/ccfast/lib/python3.9/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "alembic/env.py", line 23, in <module>
    from app.db.base import Base  # noqa
ModuleNotFoundError: No module named 'app'
```

Looking at the way the source code is organized, I'm not sure it can work unless PYTHONPATH is modified or the alembic folder is moved. Can anyone shed some light on this?

**Comment by szymonpru** [comment]
For pycharm:
right click on the backend module -> Mark directory as - >Sources root
right click on the app module -> Mark directory as - >Sources root
right click on the app.app module -> Mark directory as - >Sources root

It should works now.

**Comment by Fingel** [comment]
> For pycharm:
> right click on the backend module -> Mark directory as - >Sources root
> right click on the app module -> Mark directory as - >Sources root
> right click on the app.app module -> Mark directory as - >Sources root
> 
> It should works now.

This issue doesn't have anything to do with Pycharm, this is just trying to run alembic from a terminal as per the instructions.

**Comment by abrichr** [comment]
I've found that you need to issue alembic commands from within the backend container:

```
%  docker-compose exec backend bash       
root@6877cea23e6a:/app# alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
root@6877cea23e6a:/app#
```

**Comment by Fingel** [comment]
I see, it looks like this project is meant to be developed while being served from within a docker container.

I've found that workflow to be more inconvenient than it is worth, and would prefer personally to just work with the source tree directly. I'll close this since it looks like it was never actually meant to work.

**Comment by tiangolo** [comment]
Thanks for the help here everyone! :clap: :bow: 

Thanks for reporting back and closing the issue :+1:

**Comment by abrichr** [comment]
I believe the recommendation is to uncomment the default `command: /start-reload.sh` in `docker-compose.override.yml` and uncomment this line above it:

https://github.com/fastapi/full-stack-fastapi-template/blob/master/docker-compose.override.yml#L63

This way the container sleeps forever and you can connect to it. Not ideal but it works.

I thought this was documented somewhere but I can't find the source right now.

**Comment by userfhy** [comment]
If you don't use the docker container to run.
Then entering the project root directory, run the following command in the terminal.

```bash
cd backend
export PYTHONPATH=$PWD
bash scripts/prestart.sh
```

```bash
$ bash scripts/prestart.sh
+ python app/backend_pre_start.py
INFO:__main__:Initializing service
INFO:__main__:Starting call to '__main__.init', this is the 1st time calling it.
INFO:__main__:Service finished initializing
+ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> e2412789c190, Initialize models
INFO  [alembic.runtime.migration] Running upgrade e2412789c190 -> 9c0a54914c78, Add max length for string(varchar) fields in User and Items models
INFO  [alembic.runtime.migration] Running upgrade 9c0a54914c78 -> d98dd8ec85a3, Edit replace id integers in all models to use UUID instead
INFO  [alembic.runtime.migration] Running upgrade d98dd8ec85a3 -> 1a31ce608336, Add cascade delete relationships
+ python app/initial_data.py
INFO:__main__:Creating initial data
INFO:__main__:Initial data created
```

**Comment by abrichr** [comment]
I think all you need is:

```
cd backend
source .venv/bin/activate
alembic upgrade head
```
