### ISSUE TITLE
About the frontend framework

### ISSUE THREAD

**Issue by VivianSolide** [tiangolo/full-stack-fastapi-postgresql#328]
Hi there,

Thank you so much to provide this generator!
I'm just wondering if you'll later let to the user the ability to select the frontend framework?

I mean, it could have been great for me to select nuxtjs instead of vue.

An other related issue is the ability to disable the frontend part also.
In meantime, It's well explained inside the README.md : not a big deal!

Cheers,

**Comment by PhE** [comment]
See #357  for a fork with a nuxtjs integration (not selectable and with tailwind in place of vuetify).

**Comment by VivianSolide** [comment]
Thanks for warning!

**Comment by tiangolo** [comment]
Thanks for the help here @PhE ! 👏  🙇 

Thanks for reporting back and closing the issue @VivianSolide  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
