### ISSUE TITLE
docker build curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused /bin/sh: 1: poetry: not found

### ISSUE THREAD

**Issue by zhangwk02** [tiangolo/full-stack-fastapi-postgresql#330]
when i run docker-compose up;
raise error like that curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
/bin/sh: 1: poetry: not found
but in my host run  RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py is ok！！
why?

**Comment by tiangolo** [comment]
I assume you solved it, thanks for closing the issue :+1:

**Comment by kingyue737** [comment]
I meet the same issue. How did you solve it?

**Comment by zhangwk02** [comment]
> I meet the same issue. How did you solve it?

download the file 「https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py 」，after uplaod it to your pkg  then curl from your pkg
