### ISSUE TITLE
traefik proxy does not start.

### ISSUE THREAD

**Issue by luanjubica-helius** [tiangolo/full-stack-fastapi-postgresql#332]
Hello,
So I started up the project in a Digital Ocean docker droplet. After some back and fourth I got the Traefik public running,  and started stack inside the droplet 

I have this situation :
>htt-online_backend_1        /start.sh                        Up         80/tcp
>htt-online_celeryworker_1   bash /worker-start.sh            Up
>htt-online_db_1             docker-entrypoint.sh postgres    Up         5432/tcp
>htt-online_flower_1         flower --broker=amqp://gue ...   Exit 128
>htt-online_frontend_1       nginx -g daemon off;             Up         80/tcp
>htt-online_pgadmin_1        /entrypoint.sh                   Exit 128
>htt-online_proxy_1          /traefik --docker  --docke ...   Exit 128
>htt-online_queue_1          docker-entrypoint.sh rabbi ...   Up         15691/tcp, 15692/tcp, 25672/tcp, 4369/tcp, 5671/tcp, 5672/tcp

as you can see the proxy has exited .

The other public Traefic instance is ok : 
>fxezsix7b3g5        traefik_traefik.1       traefik:v2.2        docker-s-1vcpu-1gb-nyc1-01   Running             Running 19 minutes ago

any advice?

**Comment by luanjubica-helius** [comment]
Problem solved with the latest version of docker-compose.yml from this repo.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
