### ISSUE TITLE
How to recover app database

### ISSUE THREAD

**Issue by edkazcarlson** [tiangolo/full-stack-fastapi-postgresql#335]
Not sure how, but I somehow deleted my app database, is there an easy way to recover the default app database?
Also when I tried to do db migrations (before I accidentally deleted the app database), I couldn't access my backend container to run the `$ alembic revision --autogenerate -m "Add column last_name to User model"` command due to it crashing when I try to start it with docker-compose.  I know/think it's crashing due to adding a new column to my user table, but this feels like a catch 22, and I'm not sure what I'm doing wrong.  
Specifically, I'm adding the line `pfp_Path = Column(String, default = "Default.bmp")` in my user.py model and the line `pfp_Path: str` in my user.py schema, as well as adding the line `pfp_Path = 'Default.bmp'` in my db_obj in create in the CRUDUser.py file, is there something I'm missing?
Sorry if this is the wrong place to ask

**Comment by sbadisa** [comment]
How did you resolve this?

**Comment by edkazcarlson** [comment]
Looking back, I was a little vague in my wording.
If you are looking to recover data that was in the DB, I don't know/think you are able to do that if you delete it.
One thing that seemed to work in order to reset the database completely along with flattening the alembic revisions was to
 - Delete alembic folder and alembic.ini
 - remove app db
 - restart docker images
 - alembic init in backend/app
 This seemed to fix the problems I was having, and also "flattened" all the alembic revisions into one.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue @edkazcarlson  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
