### ISSUE TITLE
Live Uvicorn Debugging......b/c I had a pydantic validation error.

### ISSUE THREAD

**Issue by MrYutz** [tiangolo/full-stack-fastapi-postgresql#337]
I am new to the project but fell in love from the get-go.  Hopefully, this will help someone else out.  Sorry in advance if I should be posting this somewhere else.

I was getting the following error, so I figured out how to enabled live debugging inside the docker-compose _backend_ container.

Error:
`pydantic.error_wrappers.ValidationError: 1 validation error for Instrument
response
  value is not a valid dict (type=type_error.dict)
`

The problem was that I had this in my schema file:

`    class Config:
        orm_mode : True`

Those who are more astute than I will realize this should have been:

`    class Config:
        orm_mode = True`

Stupid typo, but it wasn't caught by the linter, and didn't cause any errors at run time.

So anyway I got live debugging working.  It was a hack of [Adrien Cacciaguerra's](https://blog.theodo.com/2020/05/debug-flask-vscode/) solution.  The only downside that this setup gives me is I have to set the DEBUGGER to False and rebuild if I don't want the debugger active.  Otherwise, it just sits and waits for VSCode to connect before actually running anything on the server.

1. Create \backend\app\app\debugger.py with the following code:

```
# debugger.py
from os import getenv

def initialize_flask_server_debugger_if_needed():
    if getenv("DEBUGGER") == "True":
        import multiprocessing

        if multiprocessing.current_process().pid > 1:
            import debugpy

            debugpy.listen(("0.0.0.0", 10001))
            print("⏳ VS Code debugger can now be attached, press F5 in VS Code ⏳", flush=True)
            debugpy.wait_for_client()
            print("� VS Code debugger attached, enjoy debugging �", flush=True)
```

2. Edit \backend\app\app\main.py with the following code:

```
from app.debugger import initialize_flask_server_debugger_if_needed

initialize_flask_server_debugger_if_needed()
```

This made my whole file look like this:

```
from fastapi import FastAPI
from starlette.middleware.cors import CORSMiddleware

from app.api.api_v1.api import api_router
from app.core.config import settings

from app.debugger import initialize_flask_server_debugger_if_needed
initialize_flask_server_debugger_if_needed()

app = FastAPI(
    title=settings.PROJECT_NAME, openapi_url=f"{settings.API_V1_STR}/openapi.json"
)

# Set all CORS enabled origins
if settings.BACKEND_CORS_ORIGINS:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=[str(origin) for origin in settings.BACKEND_CORS_ORIGINS],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

app.include_router(api_router, prefix=settings.API_V1_STR)
```

3. add DEBUGGER=True to your .env file

4. add port 10001 to your \docker-compose-override.yml

```
backend:
    ports:
      - "8888:8888"
      - "10001:10001"
```

5. Add `debugpy = "^1.2"` to your pyproject.toml so the debugger gets added to the docker image.

6. Perform a docker-compose build to incorporate the changes.

7. Create a new debug config in VSCode:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 10001
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}/backend/app",
                    "remoteRoot": "/app"
                }
            ]
        }
    ]
}

```
8. Press F5 in VSCode to run the debugger with the new config.

9. You should get a message in the DEBUG CONSOLE that says:

`� VS Code debugger attached, enjoy debugging �
`

**Comment by wilson-romero** [comment]
Gracias es de mucha ayuda

**Comment by tiangolo** [comment]
Thanks for writing about it and closing the issue afterwards @MrYutz! 🚀 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
