### ISSUE TITLE
Help Login

### ISSUE THREAD

**Issue by subspider** [tiangolo/full-stack-fastapi-postgresql#339]
I just did follow the steps and made it possible to run but no matter what password I give or input I can enter the backend. 

Is there anything I should be doing

**Comment by pramadito** [comment]
try make sure your first_superuser is email or just don't set it. 

also on other note: i can't login to front end either after rebuild the project from scratch. i can enter postgres db tho with it

**Comment by bennettwbrown** [comment]
I experienced the same issue on my first try. Turns out I missed this step during the setup as it is tucked about half of the way down in the documentation. 

## Frontend development
* Enter the `frontend` directory, install the NPM packages and start the live server using the `npm` scripts:

```bash
cd frontend
npm install
npm run serve
```

After that everything ran as expected

**Comment by pramadito** [comment]
ok i did found the problem, if you **regenerating the project or restarting the project** make sure you **drop all the previous database table** from postgres data in the docker. it's really hidden in the docker.  here's what i did solve the issue using this [stackoverflow method](https://stackoverflow.com/questions/43618517/docker-postgress-clear-all-data)

**Comment by subspider** [comment]
@pramadito that was the correct answer you have to make docker-compose to delete everything cus it saves the state. I guess is more I'm a newbie in docker

**Comment by tiangolo** [comment]
Thanks for the help here everyone! 👏  🙇 

Thanks for reporting back and closing the issue @subspider  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
