### ISSUE TITLE
[Question] How to deploy this project template on github page?

### ISSUE THREAD

**Issue by pramadito** [tiangolo/full-stack-fastapi-postgresql#341]
i am trying to deploy this project template on github pages for learning it, any idea how to do it? 

should i use that same method as dockerswarm.rocks cluster method?

**Comment by Mause** [comment]
You can't deploy executable code to Github pages?

**Comment by tiangolo** [comment]
Thanks for the help here @Mause ! 👏  🙇 

Thanks for coming back and closing the issue @pramadito  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
