### ISSUE TITLE
Issue with the get_current_user method for authenaticaion.

### ISSUE THREAD

**Issue by RyanPapazoglou** [tiangolo/full-stack-fastapi-postgresql#342]
## Description

I am using this project as an API only application and so I've stripped the frontend. I am able to get everything up and running and am even able to authenticate in the `/docs` endpoint with my default superusers. However, after authenticating and testing any of the endpoints that require auth I get the response `Could not validate credentials` which is thrown from the `def get_current_user()` method in deps.py. 

I've done step-thru debugging and am able to see that the `payload` is successfully extracted from jwt.decode() method, but this line: `token_data = schemas.TokenPayload(**payload)` doesn't seem to work. The token_data is never populated and an exception is thrown. 

Has anyone run into a similar issue?

EDIT: The Token Payload schema and return values for jwt.decode() do not match. Why is the `class TokenPayload(BaseModel):` expecting sub to be of type `Integer`? Is there a reason for this? I have not changed anything with respect to authentication and am wondering if something might be off.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
