### ISSUE TITLE
Updating Just the username will fail

### ISSUE THREAD

**Issue by vishalsingh9423** [tiangolo/full-stack-fastapi-postgresql#350]
https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/490c554e23343eec0736b06e59b2108fdd057fdc/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/crud/crud_user.py#L34

Whenever I try updating the Full Name for a user Via the UI the operation gets stuck in between. Checked the backend logs and got this. 

backend logs:
$ docker logs --tail 100 mb_backend_1
> INFO:     172.18.0.5:45150 - "PUT /api/v1/users/1 HTTP/1.1" 500 Internal Server Error
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
>     result = await app(self.scope, self.receive, self.send)
>   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
>     return await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 146, in __call__
>     await super().__call__(scope, receive, send)
>   File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
>     raise exc from None
>   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
>     await self.app(scope, receive, _send)
>   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
>     await self.simple_response(scope, receive, send, request_headers=headers)
>   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 140, in simple_response
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
>     raise exc from None
>   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
>     await self.app(scope, receive, sender)
>   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
>     await route.handle(scope, receive, send)
>   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
>     response = await func(request)
>   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 197, in app
>     dependant=dependant, values=values, is_coroutine=is_coroutine
>   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
>     return await run_in_threadpool(dependant.call, **values)
>   File "/usr/local/lib/python3.7/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
>     return await loop.run_in_executor(None, func, *args)
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "./app/api/api_v1/endpoints/users.py", line 152, in update_user
>     user = crud.user.update(db, db_obj=user, obj_in=user_in)
>   File "./app/crud/crud_user.py", line 34, in update
>     if update_data["password"]:
> KeyError: 'password'
> INFO:     172.18.0.5:45152 - "GET /api/v1/users/ HTTP/1.1" 200 OK

Also, when I try updating the full name and password together things work both the values get updated to the DB.
Probably we need to check whether update_data has a password key or not.

**Comment by thomas-chauvet** [comment]
This is a known issue. PRs are pending to fix this. You can check PR #348.

FYI, you just need to replace `if update_data["password"]:` by `if "password" in update_data: # Need to check for password key`.

**Comment by vishalsingh9423** [comment]
Oh. The review is out for it. Thanks, Thomas

**Comment by tiangolo** [comment]
Thanks for the help here @thomas-chauvet ! 👏  🙇 

Thanks for reporting back and closing the issue @we-shall  👍

I have a big revamp of this project pending, using SQLModel and other things. :nerd_face: 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
