### ISSUE TITLE
Missing file: start-reload.sh

### ISSUE THREAD

**Issue by abrichr** [tiangolo/full-stack-fastapi-postgresql#352]
`docker-compose.override.yml` references a file named `start-reload.sh`:

https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/docker-compose.override.yml#L54:

> command: /start-reload.sh

But this file is nowhere to be found:

```
full-stack-fastapi-postgresql % find . -name "*.sh"
./scripts/dev-fsfp-back.sh
./scripts/dev-fsfp.sh
./scripts/dev-link.sh
./scripts/test.sh
./scripts/discard-dev-files.sh
./{{cookiecutter.project_slug}}/backend/app/prestart.sh
./{{cookiecutter.project_slug}}/backend/app/scripts/test-cov-html.sh
./{{cookiecutter.project_slug}}/backend/app/scripts/format-imports.sh
./{{cookiecutter.project_slug}}/backend/app/scripts/lint.sh
./{{cookiecutter.project_slug}}/backend/app/scripts/test.sh
./{{cookiecutter.project_slug}}/backend/app/scripts/format.sh
./{{cookiecutter.project_slug}}/backend/app/tests-start.sh
./{{cookiecutter.project_slug}}/backend/app/worker-start.sh
./{{cookiecutter.project_slug}}/scripts/build-push.sh
./{{cookiecutter.project_slug}}/scripts/build.sh
./{{cookiecutter.project_slug}}/scripts/deploy.sh
./{{cookiecutter.project_slug}}/scripts/test-local.sh
./{{cookiecutter.project_slug}}/scripts/test.sh
```

I am similarly unable to locate this file in the generated project:

```
# find . -name "*.sh"
./pull-and-deploy.sh
./scripts/deploy.sh
./scripts/build.sh
./scripts/build-push.sh
./scripts/test.sh
./scripts/test-local.sh
./backend/app/scripts/test-cov-html.sh
./backend/app/scripts/lint.sh
./backend/app/scripts/format-imports.sh
./backend/app/scripts/test.sh
./backend/app/scripts/format.sh
./backend/app/worker-start.sh
./backend/app/tests-start.sh
./backend/app/prestart.sh
```

Is the `yml` file incorrect, or is this file being generated at runtime somehow?

**Comment by vishalsingh9423** [comment]
The start-reload.sh file is present inside the base image. 

check the readme file: https://github.com/tiangolo/full-stack-fastapi-postgresql/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D 

> There is also a command override that runs /start-reload.sh (included in the base image) instead of the default /start.sh (also included in the base image). It starts a single server process (instead of multiple, as would be for production) and reloads the process whenever the code changes. Have in mind that if you have a syntax error and save the Python file, it will break and exit, and the container will stop. After that, you can restart the container by fixing the error and running again:

**Comment by abrichr** [comment]
I saw that, but I'm not sure I understand what is meant by "base image" in this context. Can you please clarify?

**Comment by abrichr** [comment]
Can you please clarify what "base image" is referring to in this context?

**Comment by tiangolo** [comment]
Thanks for the help here @we-shall ! 👏  🙇 

Thanks for reporting back and closing the issue @abrichr  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
