### ISSUE TITLE
how is the database `app` ( `create database ...` ) firstly created ?

### ISSUE THREAD

**Issue by gerazenobi** [tiangolo/full-stack-fastapi-postgresql#361]
Hi there,

I have been taking a look at the generated code/scripts/etc for a while now, and was wondering how is that the database `app` is firstly created ?  It would seem the code and scripts regarding initialisation would expect for `app` to be there already if I am not mistaken ? Does it have to be created manually ? I didn't find a reference to this part within the `README` file.

I did run the project and was able to see it working, but it was a while back and I don't remember if I had instinctively (and blindly/automatically) created the database myself without paying too much attention to this step.

Thanks in avance.

**Comment by haviduck** [comment]
alembic :)
somewhere around here:
https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/490c554e23343eec0736b06e59b2108fdd057fdc/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/db/init_db.py#L12

**Comment by gerazenobi** [comment]
hi @haviduck , thanks for your response. But you are talking about the schema/tables. I was talking about the database itself (note that alembic will error if the database is not created beforehand)

also, the code you pointed out not only assumes the database is created but the tables as well.

**Comment by gerazenobi** [comment]
for future readers: the postgres container image will create the database ( `POSTGRES_DB` ) when first started:

> POSTGRES_DB
This optional environment variable can be used to define a different name for the default database that is created when the image is first started. If it is not specified, then the value of POSTGRES_USER will be used.

which it is being passed through the `.env` file:

```yaml
  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
```

**Comment by tiangolo** [comment]
Thanks for the help here @haviduck ! 👏  🙇 

Thanks for reporting back and closing the issue @gerazenobi  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
