### ISSUE TITLE
start-reload.sh is missing in the backend base docker image 

### ISSUE THREAD

**Issue by tbikeev** [tiangolo/full-stack-fastapi-postgresql#362]
Local development build through docker-compose
via `docker-compose up -d` (everything by default) creates failing backend image:
`/entrypoint.sh: 46: exec: /start-reload.sh: not found`

**Comment by tbikeev** [comment]
Stupid mistake of mine. Had old image with same name (from full-stack project). All work when images are rebuilt fresh.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
