### ISSUE TITLE
change theme

### ISSUE THREAD

**Issue by mshafiey** [tiangolo/full-stack-fastapi-postgresql#378]
I'm new on Vue js. who can help me change the theme colour?
in fact, I don't know I should start from where?

**Comment by haviduck** [comment]
around here :) 

https://vuetifyjs.com/en/features/theme/

https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/frontend/src/plugins/vuetify.ts

**Comment by mshafiey** [comment]
Thanks, mate
