### ISSUE TITLE
include files with password in .gitignore

### ISSUE THREAD

**Issue by erdnax123** [tiangolo/full-stack-fastapi-postgresql#383]
for security reasons:

create .env.local and add to .gitignore, move all config with passwords to .env.local

add cookiecutter-config-file.yml to .gitignore

**Comment by tiangolo** [comment]
Yep, you can definitely do that! Nevertheless, that would be directly on your repo, not in this one that is the template with the defaults to get something runnable right after cloning. Thanks for the interest! :coffee:
