### ISSUE TITLE
How can I add seed data?

### ISSUE THREAD

**Issue by yusuke2930** [tiangolo/full-stack-fastapi-postgresql#385]
I want to add seed data after execute migration.
For example, there is `user_types` table as master table.
I want to insert some seed data into this table.

**Comment by robertop23** [comment]
You can do that in the file https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/db/init_db.py

**Comment by yusuke2930** [comment]
@robertop23 thanks！
