### ISSUE TITLE
Poetry installer out of date

### ISSUE THREAD

**Issue by Zaffer** [tiangolo/full-stack-fastapi-postgresql#386]
The link in the read me and also the terminal output of docker compose shows:
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py 

But it's depreciated, must now be:

curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py

**Comment by laszukdawid** [comment]
I just tried "upgrading" it to `install-poetry` and it won't work. Main blocker right now is that it doesn't allow to use global env (https://github.com/python-poetry/poetry/issues/4187) which is necessary backend.

They seem to went to fast with "deprecation" message. It's only in the readme and their official website still has "get-poetry" script.

**Comment by tiangolo** [comment]
Thanks! It should be working now that it's all updated. :nerd_face:
