### ISSUE TITLE
Flower (Celery) Dies on Fresh Project

### ISSUE THREAD

**Issue by mgbvox** [tiangolo/full-stack-fastapi-postgresql#403]
After configuring my cookiecutter project and running ```docker-compose up -d``` as specified, everything starts EXCEPT for the `flower` service, which prints the following message:
```
ERROR: for flower  Cannot start service flower: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "--broker=amqp://guest@queue:5672//": stat --broker=amqp://guest@queue:5672//: no such file or directory: unknown
```

Cursory internet searches make me think that this is using the wrong broker address? Looking at my rabbitmq server (which - by the way - I had no idea I had to install and only inferred from the above internet search) logs, it appears that my broker is running at `rabbit@localhost`:
```
*excerpt*
2021-07-21 16:38:28.986 [info] <0.274.0> Running boot step cluster_name defined by app rabbit
2021-07-21 16:38:28.986 [info] <0.274.0> Running boot step direct_client defined by app rabbit
2021-07-21 16:38:28.986 [info] <0.274.0> Running boot step rabbit_management_load_definitions defined by app rabbitmq_management
2021-07-21 16:38:28.987 [info] <0.548.0> Resetting node maintenance status
2021-07-21 16:38:28.987 [info] <0.44.0> Application rabbit started on node rabbit@localhost
2021-07-21 16:38:29.034 [info] <0.44.0> Application rabbitmq_management_agent started on node rabbit@localhost
*more logs...*
```

However, changing occurrences of `guest@queue` to `rabbit@localhost` doesn't fix the error. 

Side note: I have no prior experience working with Celery, and am honestly confused as to why it's included in this stack - would love to be enlightened.

**Comment by markkvdb** [comment]
This problem is related to the v1.0 release of Flower. I'm not quite sure what Flower changed but it's based to set the image version explicitly to a version that's working. In my case, I set the flower image to `flower:0.9.7` since this is the last version that still works for me.

**Comment by waclock** [comment]
Fixing version to 0.9.7 worked for me as well.

**Comment by mgbvox** [comment]
@markkvdb and @waclock thank you! This worked for me.

**Comment by limsammy** [comment]
@markkvdb thanks, fixed for me as well. Should create a PR :)

**Comment by AlanMars** [comment]
Fix solution:

in {{cookiecutter.project_slug}}/docker-compose.yml

  flower:
    image: mher/flower**:0.9.7**
