### ISSUE TITLE
after the new windows update i'm getting this error..!!

### ISSUE THREAD

**Issue by alwinSGA** [tiangolo/full-stack-fastapi-postgresql#408]
$docker-compose up

time="2021-07-29T23:02:21+05:30" level=warning msg="The TAG variable is not set. Defaulting to a blank string."
time="2021-07-29T23:02:21+05:30" level=warning msg="The INSTALL_DEV variable is not set. Defaulting to a blank string."
time="2021-07-29T23:02:21+05:30" level=warning msg="The TAG variable is not set. Defaulting to a blank string."
time="2021-07-29T23:02:21+05:30" level=warning msg="The INSTALL_DEV variable is not set. Defaulting to a blank string."
time="2021-07-29T23:02:21+05:30" level=warning msg="The TAG variable is not set. Defaulting to a blank string."
time="2021-07-29T23:02:21+05:30" level=warning msg="The FRONTEND_ENV variable is not set. Defaulting to a blank string."
time="2021-07-29T23:02:21+05:30" level=warning msg="The TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL variable is not set. Defaulting to a blank string."
services.backend.build.args.INSTALL_DEV must be a string, number or null

Getting this error after creating application using cookiecutter.

Also my existing working project also getting same error. i have updated my windows recently not sure it's because of that.
my existing project was working fine before updating windows, after the update it's stop working and getting this error. 
so i try to create new project by using the same cookiecutter. there also i got the same error.
i had reinstalled docker and tried still getting same error.

time="2021-07-29T22:42:01+05:30" level=warning msg="The TAG variable is not set. Defaulting to a blank string."
time="2021-07-29T22:42:01+05:30" level=warning msg="The INSTALL_DEV variable is not set. Defaulting to a blank string."
time="2021-07-29T22:42:01+05:30" level=warning msg="The TAG variable is not set. Defaulting to a blank string."
time="2021-07-29T22:42:01+05:30" level=warning msg="The INSTALL_DEV variable is not set. Defaulting to a blank string."
time="2021-07-29T22:42:01+05:30" level=warning msg="The TAG variable is not set. Defaulting to a blank string."
time="2021-07-29T22:42:01+05:30" level=warning msg="The FRONTEND_ENV variable is not set. Defaulting to a blank string."time="2021-07-29T22:42:01+05:30" level=warning msg="The TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL variable is not set. Defaulting to a blank string."

cloud you someone please help me on this. my project got stopped, due to this issue. The same code is working fine in linux and MAC OS.

**Comment by karolzlot** [comment]
1. Open `Docker Desktop`
2. Go to `Settings`
3. Go to `Experimental Features`
4. Uncheck `Use Docker Compose V2`

As of now I don't know how to modify this project to make it compatible with docker-compose V2, but it works ok with V1.



![image](https://user-images.githubusercontent.com/11590960/128097299-2c44bcb0-5083-453c-b65e-e2925d140e8f.png)

**Comment by alwinSGA** [comment]
yes it's working now Thank you so much..!

**Comment by shaunmulligan** [comment]
It seems the new compose v2 uses a more strict yaml parser. I found that if I wrapped the boolean defaults in quotes so they are interpreted as strings then it worked correctly. e.g.:

```
      args:
        INSTALL_DEV: ${INSTALL_DEV-"false"}
```
