### ISSUE TITLE
How to configure celery workers?

### ISSUE THREAD

**Issue by duz-sg** [tiangolo/full-stack-fastapi-postgresql#42]
I'm currently playing around the celery workers, even though I have followed the Celery Worker official guide, I could increase neither the worker count nor the concurrency count.

Below is my change in ```worker-start.sh```
```shell
# celery worker -A app.worker -l info -Q main-queue -c 4
celery worker -A app.worker --loglevel=INFO -O fair --concurrency=2 -n worker1@%h 
celery worker -A app.worker --loglevel=INFO -O fair --concurrency=2 -n worker2@%h
```
I'm expecting to start the 2 workers, each can fork 2 processes, however, after ```docker-compose restart```, I can only get a single worker, with one single process. I tried to add several tasks, each took 180 seconds, they can only be executed one after another, because I have only one worker to run them in sequential.

Any other places shall I look into to get more workers/processes? Thanks.

**Comment by duz-sg** [comment]
Update on this, it should be a novice issue. After changing the ```worker-start.sh```, it's not automatically updated, it has to be copied into the container after a build action.

**Comment by tiangolo** [comment]
I'm glad you solved your problem. Thanks for reporting back and closing the issue.
