### ISSUE TITLE
How can I deploy Google Cloud Run?

### ISSUE THREAD

**Issue by yusuke2930** [tiangolo/full-stack-fastapi-postgresql#442]
Did anyone succeed in deploying to cloud run?

**Comment by a-coello** [comment]
Hi. I have the problem, too, deploying in google cloud. It's deploying sort of fine but when I go to an endpoind which uses the sqlmodel, it crash. "sqlmodule not found". (Is in requirements.txt)

**Comment by yusuke2930** [comment]
@a-coello I resolved this issue, to deploy to cloud run.
But I couldn't confirm "sqlmodule not found"
