### ISSUE TITLE
 QueuePool limit of size 5 overflow 10 reached

### ISSUE THREAD

**Issue by jrlopes2005** [tiangolo/full-stack-fastapi-postgresql#459]
Hi,

I got this error:
     QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error.....).

Im using sqlalchemy 1.4 async session using dependency injection

Thanks.

**Comment by AhmedSam3r** [comment]
@jrlopes2005 how did you solve this issue ?
