### ISSUE TITLE
celeryworker.dockerfile have to change.

### ISSUE THREAD

**Issue by po2son** [tiangolo/full-stack-fastapi-postgresql#479]
celeryworker.dockerfile have to change.

```
# Install Poetry - before
# RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python && \
#    cd /usr/local/bin && \
#    ln -s /opt/poetry/bin/poetry && \
#    poetry config virtualenvs.create false

```
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

```
# Install Poetry - changed
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3
ENV PATH="/opt/poetry/bin:$PATH"
RUN poetry config virtualenvs.create false
```

**Comment by rabarbra** [comment]
Same with backend.dockerfile

**Comment by willingc** [comment]
See PRs https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/524 and https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/529 for the corrected files if you want to take a look.

**Comment by tiangolo** [comment]
Thanks! This was fixed in https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/480 🤓 

And thanks a lot for the help @willingc 🙇
