### ISSUE TITLE
error when run docker compose up ??

### ISSUE THREAD

**Issue by zergreen** [tiangolo/full-stack-fastapi-postgresql#488]
I'm beginner use command with this work flow

```
pip install cookiecutter
cookiecutter https://github.com/tiangolo/full-stack-fastapi-postgresql

# cd to project and run with docker compose up
docker compose up
```

[error-docker-compose](https://drive.google.com/file/d/17H0hYnY7Nwzin8CDANcKOLBA8xpeSMsl/view?usp=sharing)

**Comment by dgroo** [comment]
As I am also working through this/experimenting - changing the URLs in:
celeryworker.dockerfile
backend.dockerfile

from
`https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py`
to
`https://install.python-poetry.org/`

Should work.

**Comment by ibojicic** [comment]
In backend/app/backend.dockerfile and celeryworker.dockerfile change poetry installation section to:

`RUN curl -sSL https://install.python-poetry.org | python3 -  && \
    cd /usr/local/bin && \
    ln -s /root/.local/bin/poetry && \
    poetry config virtualenvs.create false`

**Comment by epicwhale** [comment]
> As I am also working through this/experimenting - changing the URLs in: celeryworker.dockerfile backend.dockerfile
> 
> from `https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py` to `https://install.python-poetry.org/`
> 
> Should work.

This did the job. More precisely, your end result should be:

```
# Install Poetry
RUN curl -sSL https://install.python-poetry.org/ | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false```

**Comment by willingc** [comment]
See PRs https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/524 and https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/529 for the corrected files if you want to take a look.

**Comment by tiangolo** [comment]
Thanks! This was solved in https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/480 🎉 

And thanks @willingc! 🍨
