### ISSUE TITLE
backend.dockerfile # Install Poetry source not found

### ISSUE THREAD

**Issue by wi-wi** [tiangolo/full-stack-fastapi-postgresql#495]
in backend.dockerfile # Install Poetry does not execute because 
https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
not found 404

**Comment by Pr0curo** [comment]
as a workaround you can use the current installation script found under `https://install.python-poetry.org/` as a replacement of the 'old' script (replace in Line 6 in `backend.dockerfile` and `celeryworker.dockerfile`).

After replacing it the backend was fine

**Comment by pankajarm** [comment]
Thank you @Pr0curo , i was having same issue, the workaround of updating backend.dockerfile and celeryworker.dockerfile with below works:
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

**Comment by MhdHabboub** [comment]
thanks all, however, I'm getting this error when trying @pankajarm  solution
```
 => [3/7] RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python &&     cd /usr/local/bin &&     ln -s /opt/poetry/bin/poetry &&     poetry config virtualenvs.create false                      35.1s 
failed to solve: executor failed running [/bin/sh -c npm run build]: exit code: 1
```

**Comment by randy-wong** [comment]
> thanks all, however, I'm getting this error when trying @pankajarm solution
> 
> ```
>   => [3/7] RUN curl -sSL https://install.python-poetry.org/ | POETRY_HOME=/opt/poetry python &&     cd /usr/local/bin &&     ln -s /opt/poetry/bin/poetry &&     poetry config virtualenvs.create false                     26.4s 
> failed to solve: executor failed running [/bin/sh -c npm run build]: exit code: 1
> ```

Try:

`RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/etc/poetry python3 `

**Comment by tsaroff** [comment]
> in backend.dockerfile # Install Poetry does not execute because https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py not found 404

You need to change the link to (get-poetry.py  -> install-poetry.py ):

```
# Install Poetry
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false
```

**Comment by willingc** [comment]
See PRs https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/524 and https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/529 for the corrected files if you want to take a look.

**Comment by tiangolo** [comment]
Thanks! This was solved in https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/480 🎉 

And thanks @willingc! 🌯
