### ISSUE TITLE
Question: Crud db injection design.

### ISSUE THREAD

**Issue by koutsilis1999** [tiangolo/full-stack-fastapi-postgresql#498]
Hello there,
I was going through the code and wanted to know why the crud objects inject the db session in each method instead of the constructor. Is there a benefit to this design? 

for example:
instead of 
```python3 
class CRUDBase(Generic[ModelType, CreateSchemaType, UpdateSchemaType]):
    def __init__(self, model: Type[ModelType]):
        self.model = model

    def get(self, db: Session, id: Any) -> Optional[ModelType]:
        return db.query(self.model).filter(self.model.id == id).first()

    def get_multi(
        self, db: Session, *, skip: int = 0, limit: int = 100
    ) -> List[ModelType]:
        return db.query(self.model).offset(skip).limit(limit).all()

```

it could be:
```python3
class CRUDBase(Generic[ModelType, CreateSchemaType, UpdateSchemaType]):
    def __init__(self, model: Type[ModelType], db: Session):
        self.model = model
        self.db = db

    def get(self, id: Any) -> Optional[ModelType]:
        return self.db.query(self.model).filter(self.model.id == id).first()

    def get_multi(
        self, skip: int = 0, limit: int = 100
    ) -> List[ModelType]:
        return self.db.query(self.model).offset(skip).limit(limit).all()

```

Thank you :)

**Comment by arunanshub** [comment]
Using [`deps.get_db`][db] the session object is created with each request. Storing it in the `CRUDBase` would thus be pointless.

[db]: <https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/490c554e23343eec0736b06e59b2108fdd057fdc/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/api/deps.py#L19>

**Comment by koutsilis1999** [comment]
> arunanshub

Please give a bit more context. I am just trying to understand the benefit. If we create a new CRUDBase instance in each request don't we have a new session anyways? But we can easily reuse the session if we pass it in to the contractor. For example, we can get an object and then update it with the same session. Hope this makes sense and thanks for the reply.

a bit of an example code to explain my thoughts. 
```bash
crud = CRUDBase(db,ModelFoo) 
obj = crud.get(id=1) 
updated = crud.update(obj,{"foo":"boo"}) 
```
