### ISSUE TITLE
Preferred way to move the production database to an external service (such as AWS RDS)?

### ISSUE THREAD

**Issue by omrihar** [tiangolo/full-stack-fastapi-postgresql#50]
A short question: we've been using the fullstack template for a while now and getting the hang of it slowly. We want to host our database on AWS RDS rather than internally in a docker container. Is there an easy way to configure this so that only the production URL will point to RDS, while all others still use a local docker container for development, staging and testing?

Currently one of our devs created a second env file called `env-postgres-prod.env` and changed `docker-compose.shared.env.yml` to use this instead, but this also affects the tests scripts etc...

**Comment by duz-sg** [comment]
My approach is just to update the ```env-postgres.env``` file so it uses the config of your AWS:
```
POSTGRES_SERVER=my-db.rds.amazonaws.com
POSTGRES_USER=user
POSTGRES_PASSWORD=password
POSTGRES_DB=prod
```
I don't have a stag DB, and would love to see a better solution.

**Comment by dmontagu** [comment]
You can just move the Postgres specific stuff from `docker-compose.shared.env.yml` to `docker-compose.dev.postgres.env.yml` and `docker-compose.deploy.postgres.env.yml` (Or prod/staging/dev or similar) and update your scripts/.env files to reference the desired compose files.

**Comment by tiangolo** [comment]
Thanks for the help here everyone! :clap: 

Yeah, I think the current Docker Compose files trying to eliminate any possible duplication end up separating things too granularly and making it all look more complex than it is.

You could define which set of Docker Compose files to use for each case, or even further, simplify each environment to have it's own single Docker Compose file. It would mean that some of them have some repetition of the same settings that you would have to make sure you keep in sync if you update them, but it would probably be simpler to handle...

**Comment by vherasme** [comment]
Hello. I am starting to use this. I will need to use a separate databse too, in my case google cloud. Could you please tell me how you solved the problem? The steps and or example would be great. Thanks
