### ISSUE TITLE
Error on first docker-compose

### ISSUE THREAD

**Issue by FoxBravoNL** [tiangolo/full-stack-fastapi-postgresql#506]
Hi all,

I'm trying to set up this template to modify it for usage in my local backend API, however I'm running into an error when trying to start the Docker stack.

As I'm not too experienced with Docker I'm not sure where to look for the problem. Here is the terminal output:

 > RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python &&     cd /usr/local/bin &&     ln -s /opt/poetry/bin/poetry &&     poetry config virtualenvs.create false:
#0 0.709   File "<stdin>", line 1
#0 0.709     404: Not Found
#0 0.709                  ^
#0 0.709 SyntaxError: invalid syntax
------
failed to solve: executor failed running [/bin/sh -c curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python &&     cd /usr/local/bin &&     ln -s /opt/poetry/bin/poetry &&     poetry config virtualenvs.create false]: exit code: 1

Any help is much appreciated!

Fabian

**Comment by Hossein-Roshandel** [comment]
Would you be able to share your Dockerfile as well? 
I would like to build a sample project with it and see if I can find the root cause.

**Comment by FoxBravoNL** [comment]
Hi,

Attached is the Dockerfile that is contained in the frontend folder and the two .dockerfile files in the backend folder.
Thanks for the help!

Kind Regards,

Fabian Bleeksma

**Comment by Hossein-Roshandel** [comment]
I did not receive the attachments, but don't worry. I believe that the poetry link in your Dockerfile is no longer valid. So you either have to replace it with a valid link for it to work or you can use the way that I install poetry in docker container and it is from their official website:
```Dockerfile
RUN python -c 'from urllib.request import urlopen; print(urlopen("https://install.python-poetry.org").read().decode())' | python -
RUN poetry completions bash >> ~/.bash_completion
```

I hope that this helps.

> Hi, Attached is the Dockerfile that is contained in the frontend folder and the two .dockerfile files in the backend folder. Thanks for the help! Kind Regards, Fabian Bleeksma
> […](#)
> On 29 Mar 2023 at 05:25 +0200, Hossein Roshandel ***@***.***>, wrote: Would you be able to share your Dockerfile as well? I would like to build a sample project with it and see if I can find the root cause. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by FoxBravoNL** [comment]
Hi again,

Thanks a lot for the tip, I almost got it working using your suggestion but ran into a next issue with another dependency. I was then able to actually find a fork that uses more up to date dependencies which got the build to complete.

However, now I’m running into the next issue:

vreflocalapi-celeryworker-1 | INFO:__main__:Starting call to '__main__.init', this is the 55th time calling it.
vreflocalapi-celeryworker-1 | ERROR:__main__:(psycopg2.OperationalError) could not translate host name ***@***.***" to address: Name or service not known
vreflocalapi-celeryworker-1 |
vreflocalapi-celeryworker-1 | (Background on this error at: https://sqlalche.me/e/14/e3q8)
vreflocalapi-celeryworker-1 | WARNING:__main__:Finished call to '__main__.init' after 54.314(s), this was the 55th time calling it.
vreflocalapi-proxy-1 | time="2023-03-29T20:22:49Z" level=info msg="Configuration loaded from flags."

I understand this is a different issue.. but my Google search didn’t yield much.
No problem if you’re too busy of course, but any help is still much much appreciated if you’ve got an idea what causes this.

Would be nice to get this template up and running...

Thanks again!

Kind Regards,

Fabian Bleeksma

**Comment by jimma72** [comment]
@FoxBravoNL, I came across the same issue as you.  

I fixed it by editing the backend.dockerfile and celery.dockerfile in the backend folder.  You will need to change the entry that is currently 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py' to 'https://install.python-poetry.org'.

I hope that helps!

**Comment by FoxBravoNL** [comment]
> 

Thanks! That was indeed the problem, managed to fix it by correcting the poetry url as well :)

**Comment by jimma72** [comment]
Did you have a problem with the npm run build for the frontend which happens later in the build?

**Comment by FoxBravoNL** [comment]
I didn't actually

**Comment by jimma72** [comment]
OK, thanks.  It must be an issue with my NPM build somewhere.  Thanks

**Comment by gleycerparra** [comment]
> @FoxBravoNL, I came across the same issue as you.
> 
> I fixed it by editing the backend.dockerfile and celery.dockerfile in the backend folder. You will need to change the entry that is currently 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py' to 'https://install.python-poetry.org'.
> 
> I hope that helps!

I ran into the same issue, and this unblocked me. Thank you!

**Comment by willingc** [comment]
See PRs https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/524 and https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/529 for the corrected files if you want to take a look.

**Comment by tiangolo** [comment]
Thanks! This was solved in https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/480 🎉 

And thanks @willingc! 🙇 🤗 🍪
