### ISSUE TITLE
get-poetry does not work

### ISSUE THREAD

**Issue by denpetrov** [tiangolo/full-stack-fastapi-postgresql#514]
https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/490c554e23343eec0736b06e59b2108fdd057fdc/%7B%7Bcookiecutter.project_slug%7D%7D/backend/backend.dockerfile#L6

get-poetry does not work anymore (https://python-poetry.org/docs/#installing-with-the-official-installer)

**Comment by feightwywx** [comment]
same problem

btw, #485 may fix this but it's still not merged

**Comment by linrh-dut** [comment]
update [backend/backend.dockerfile](url) and _backend/celeryworker.dockerfile_ two files
replace: 
  ```
  RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python
  cd /usr/local/bin && \
  ln -s /opt/poetry/bin/poetry && \
  poetry config virtualenvs.create false
```
to:
  ```
  RUN pip install poetry && \
  poetry config virtualenvs.create false
```

**Comment by willingc** [comment]
PRs https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/524 and https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/529 for the corrected files if you want to take a look.
