### ISSUE TITLE
Poetry URL seem to be not working inside the Dockerfile for backend and celery

### ISSUE THREAD

**Issue by jpmc216** [tiangolo/full-stack-fastapi-postgresql#518]
=> ERROR [backend:latest 3/7] RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python &&    0.5s
 => CANCELED [celeryworker:latest  1/10] FROM docker.io/library/python:3.7@sha256:d98fd1fa8fd1756bfe883b5004a60cfc428a1ce6e575652b771b66c8db222478              0.4s

Got it working by replacing this URL (https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py) with https://install.python-poetry.org in the dockerfile.

**Comment by dave-mitchell** [comment]
This worked for me as well.  Thank you for posting.

**Comment by willingc** [comment]
PRs https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/524 and https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/529 have the corrected files if you want to take a look.

**Comment by tiangolo** [comment]
Thanks! This was solved in https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/480 🎉 

And thanks @willingc! 🌮 🌮
