### ISSUE TITLE
os.getenvb() not supported on windows (used in config.py )

### ISSUE THREAD

**Issue by skrchnavy** [tiangolo/full-stack-fastapi-postgresql#52]
config.py contains code:
```
SECRET_KEY = os.getenvb(b"SECRET_KEY")
if not SECRET_KEY:
    SECRET_KEY = os.urandom(32)
```
https://docs.python.org/3.6/library/os.html#os.getenvb
> getenvb() is only available if supports_bytes_environ is True.

so possible change (windows as development platform) is:
```
if os.supports_bytes_environ:
    SECRET_KEY = os.getenvb(b"SECRET_KEY", default=os.urandom(32))
else:
    SECRET_KEY = os.urandom(32)
```

Note that also default can be provided in `os.getenv(key, default=None)`/`os.getenvb(key, default=None)` calls, other places can be then improved.

**Comment by StephenBrown2** [comment]
This should probably be changed to use the `secrets` stdlib module [since python 3.6](https://docs.python.org/3/library/secrets.html):

```py
import secrets

SECRET_KEY = os.getenv("SECRET_KEY", default=secrets.token_urlsafe(32))
```

**Comment by tiangolo** [comment]
Thanks for the report @skrchnavy and the help here @StephenBrown2 !

This should work well now that configs are handled with Pydantic settings 🎉
