### ISSUE TITLE
Poetry not found

### ISSUE THREAD

**Issue by jholla-atx** [tiangolo/full-stack-fastapi-postgresql#540]
This url 404's in `/backend/backend.dockerfile`:
```

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false
```

The recommended solution from cli output did not work either:
"Replace with https://install.python-poetry.org"

**Comment by rnoxy** [comment]
Any help with poetry installation?

**Comment by rafalmag** [comment]
In `backend/celeryworker.dockerfile` and `backend/backend.dockerfile` I had to update line 6 to:
```
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry POETRY_VERSION=1.2.0 python3 && \
```
and it resolved the problem.
Now fighting with npm...

**Comment by miketrimmel** [comment]
Solved it for me. Thx

**Comment by willingc** [comment]
See PRs https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/524 and https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/529 provide the corrected files if you want to take a look.

**Comment by tiangolo** [comment]
Thanks! This was solved in https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/480 🎉 

And thanks @willingc! ☕
