### ISSUE TITLE
docker-compose fails to solve get-poetry.py

### ISSUE THREAD

**Issue by aringa** [tiangolo/full-stack-fastapi-postgresql#543]
Running docker-compose up -d on a Mac , I get 

 => ERROR [celeryworker  3/10] RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python &&     cd /usr/local/bin &&     ln -s /opt/poetry/bin/poetry &&     poetry config virtualenvs.create false              0.8s
------
 > [celeryworker  3/10] RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python &&     cd /usr/local/bin &&     ln -s /opt/poetry/bin/poetry &&     poetry config virtualenvs.create false:
0.707   File "<stdin>", line 1
0.707     404: Not Found
0.707                  ^
0.707 SyntaxError: invalid syntax
------
failed to solve: process "/bin/sh -c curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python &&     cd /usr/local/bin &&     ln -s /opt/poetry/bin/poetry &&     poetry config virtualenvs.create false" did not complete successfully: exit code: 1

**Comment by aringa** [comment]
I figured out the file exists here very old version 1.3.2
https://raw.githubusercontent.com/python-poetry/poetry/1.3.2/get-poetry.py

No clue where that link is defined though.

**Comment by willingc** [comment]
PRs #524 and #529 provide the corrected files if you want to take a look.

**Comment by tiangolo** [comment]
Thanks! This was solved in https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/480 🤓 

And thanks @willingc! 🙇
