### ISSUE TITLE
[Question] No async endpoints in full-stack-fastapi-postgresql app?

### ISSUE THREAD

**Issue by sagrawal-idrc** [tiangolo/full-stack-fastapi-postgresql#55]
I see that the api endpoints do not have `async` handlers. Doesn't this mean that these handlers will run synchronously and won't be able to take advantage of the event loop/ async capabilities as NodeJS does? 

There might be some gap in my understanding here. If yes, kindly point me to relevant source. Thanks.

**Comment by sagrawal-idrc** [comment]
I read here now (under Very Technical Details) on https://fastapi.tiangolo.com/async/:

> When you declare a path operation function with normal def instead of async def, it is run in an external threadpool that is then awaited, instead of being called directly (as it would block the server).

I think this answers my question and I will close the issue.

**Comment by tiangolo** [comment]
That's right. Thanks for reporting back and closing the issue. 🍰🎉
