### ISSUE TITLE
CRUD utils does not have an update function

### ISSUE THREAD

**Issue by AnneNamuli** [tiangolo/full-stack-fastapi-postgresql#59]
CRUD utils does not an update function

**Comment by ebreton** [comment]
Hi @AnneNamuli 

you might want to have a look at this PR : https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/23, at least for an example :)

Manu

**Comment by AnneNamuli** [comment]
Thanks...  I finally saw it

**Comment by tiangolo** [comment]
Thanks for the help here @ebreton ! :clap: :bow: 

Thanks for reporting back and closing the issue @AnneNamuli  :+1:
