### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by AnneNamuli** [tiangolo/full-stack-fastapi-postgresql#60]
How do i create default values in the database(sqlalchemy)?

**Comment by tsh356** [comment]
When defining your SQLAlchemy models, you can specify a default parameter:
```
class Item(Base):
    __tablename__ = "item"
    id = Column(Integer, primary_key=True)
    created_at = Column(DateTime(), default=func.now())
    status = Column(String, default='open')
```

**Comment by AnneNamuli** [comment]
> When defining your SQLAlchemy models, you can specify a default parameter:
> 
> ```
> class Item(Base):
>     __tablename__ = "item"
>     id = Column(Integer, primary_key=True)
>     created_at = Column(DateTime(), default=func.now())
>     status = Column(String, default='open')
> ```

say for example column is status and the default values are (open, closed, unresolved)

**Comment by tsh356** [comment]
> > When defining your SQLAlchemy models, you can specify a default parameter:
> > ```
> > class Item(Base):
> >     __tablename__ = "item"
> >     id = Column(Integer, primary_key=True)
> >     created_at = Column(DateTime(), default=func.now())
> >     status = Column(String, default='open')
> > ```
> 
> say for example column is status and the default values are (open, closed, unresolved)

Exactly!

**Comment by tiangolo** [comment]
Thanks for the help here @tsh356 ! :clap: :bow: 

I assume you solved your problem, so thanks for coming back and closing the issue :+1:
