### ISSUE TITLE
Traefik configuration issue, some URLS being cancelled and then blocked, status code 307.

### ISSUE THREAD

**Issue by tsh356** [tiangolo/full-stack-fastapi-postgresql#61]
I have a stack deployed on AWS with Docker Swarm and Traefik. Everything works fine locally.

It appears that any URL with a query parameter is being cancelled, downgraded to http, and then blocked.

Here is a screenshot from chrome dev tools showing "/latest" endpoint returning successfully and the "/jobs?" input with query parameters being cancelled:

![image](https://user-images.githubusercontent.com/7598315/64623795-d4384480-d3a6-11e9-9dd6-49eca377f440.png)

If I navigate directly to the url in question, I get a successful response, but the same endpoint, called via axios in my vue app, gets cancelled.

The proxy logs are showing status code 307 for these requests. Here is the full log line:

```
"GET /api/jobs?descending=true&pagination=false HTTP/1.1" 307 0 "https://app.example.com/fb" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" 264 "PathPrefix-api-docs-redoc-1" "http://10.0.2.27:80" 1ms
```

For some reason, these requests are getting redirected to http and then failing.

Could this be a problem with the Traefik proxy configuration? Or axios?

UPDATE:
After digging into the redirect issue more, it seems to be an issue with trailing slashes. My requests are getting redirected to include a trailing slash. So 

```https://app.example.com/api/companies?type=customer```

becomes 

```http://app.example.com/api/companies/?type=customer```

(note the / before the ? and the https --> http). Since its now requesting an unsecure resource it gets blocked by chrome.

Why are all requests, even ones with query parameters (?) being redirected to "/" ?

Thanks in advance!

**Comment by tsh356** [comment]
The proxy logs are showing status code 307.

**Comment by tsh356** [comment]
If anyone else runs into this issue, it was solved by removing the prefix parameter from the intermediate APIRouter and typing the full route into the endpoints APIRouter decorator.

**Comment by vladkrylov** [comment]
The same when trying to POST a multipart form with a large upload file. In case of a small size (about few 100kB) everything is ok, 10 MB file causes 307 response from server side and BrokenPipeError at client side (python requests).

@tsh356 suggestion resolved the issue. Thanks!

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
