### ISSUE TITLE
/users/me returns 500 (GET/POST) - pydantic issue

### ISSUE THREAD

**Issue by McSlow** [tiangolo/full-stack-fastapi-postgresql#66]
## issue
hi, currently something seems to be wrong with the pydantic validations on the user model.
Any get/post to `/users/me` returns a 500. 
Logs:
<pre><font color="#75507B">backend_1        |</font> pydantic.error_wrappers.ValidationError: 1 validation error for User
<font color="#75507B">backend_1        |</font> response
<font color="#75507B">backend_1        |</font>   value is not a valid dict (type=type_error.dict)
</pre>

Request payload looks like a dict :)
![image](https://user-images.githubusercontent.com/1178921/64913701-182f9e80-d745-11e9-82c4-4234f2b4beeb.png)

## how to reproduce
fresh cookiecutter generated project, log with admin into frontend, change own username/email etc.

**Comment by McSlow** [comment]
ok. that was #43 .

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
