### ISSUE TITLE
[Question] Association tables

### ISSUE THREAD

**Issue by AnneNamuli** [tiangolo/full-stack-fastapi-postgresql#67]
@tiangolo, I have having trouble updating data in an association table. the function does not throw any errors but it doesnt update the field either. I copied the same logic from update function here -- `backend/app/app/crud/items.py`

**Comment by tiangolo** [comment]
I assume you solved your problem, so thanks for coming back and closing the issue :+1:

**Comment by AnneNamuli** [comment]
> I assume you solved your problem, so thanks for coming back and closing the issue

Yes, it was. Thanks for the response too
