### ISSUE TITLE
Validation error for User

### ISSUE THREAD

**Issue by escapenate** [tiangolo/full-stack-fastapi-postgresql#72]
Hi

I used the cookiecutter to create this project locally on macOS 10.14.6 and ran it without making any changes.

I ran into the following issue with the API (and consequently the frontend):
```
backend_1        | pydantic.error_wrappers.ValidationError: 1 validation error for User
backend_1        | response -> 0
backend_1        |   value is not a valid dict (type=type_error.dict)
```

This example was with __/api/v1/users/me__ but it occurred with all APIs returning the User model.

I was able to successfully return the user in raised exceptions all the way through the backend processing, so it seems that the validation error is being raised from __db_session_middleware__ .

Adding the orm_mode property to the UserBase model seemed to fix the issue. ie.

```python
class UserBase(BaseModel):
    email: Optional[str] = None
    is_active: Optional[bool] = True
    is_superuser: Optional[bool] = False
    full_name: Optional[str] = None

    class Config:
        orm_mode = True
```

I'm not sure whether this is a bug, or something to do with my configuration or OS - but this was a completely vanilla build, so perhaps I'm not the only person to encounter this issue.

**Comment by leandroviajando** [comment]
I'm having the same issue, this is a bug

**Comment by borland667** [comment]
I had the same issue and it looks like there was a change in behavior with the latest pydantic and now it doesn't take the db models as is.

I ended up extending the BaseModel from pydantic like this:

```
 from pydantic import BaseModel

 class BasicModel(BaseModel):
 
    class Config:
        orm_mode = True
```
And using BasicModel in all my pydantic models.

**Comment by tiangolo** [comment]
Thanks for the report and the discussion here, everyone!

This should be fixed in `master` now. :tada: 

@escapenate may we close this issue now?

**Comment by escapenate** [comment]
Works perfectly - thanks @tiangolo and @br3ndonland
