### ISSUE TITLE
Does this work??

### ISSUE THREAD

**Issue by leandroviajando** [tiangolo/full-stack-fastapi-postgresql#73]
I copied the cookiecutter link into my terminal, there were no errors and once it was done I tried to log in but only get 404, and all of the other links /api, /docs, /redoc also only give 404

**Comment by leandroviajando** [comment]
A few minutes later, the above now work; not sure what's going on here :S

**Comment by tiangolo** [comment]
I assume you solved your problem, so thanks for coming back and closing the issue :+1:
