### ISSUE TITLE
Upgrade for traefik 2.x

### ISSUE THREAD

**Issue by vlcinsky** [tiangolo/full-stack-fastapi-postgresql#81]
The code is using [Traefik v1.7](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/b96d78db99d8c4f37f0df64df587ffebda4bfc56/%7B%7Bcookiecutter.project_slug%7D%7D/docker-compose.shared.admin.yml#L10)

Consider upgrading to Traefik 2.x. 

Note, that the model of Traefik 2.x has changed.

**Comment by laurentS** [comment]
Should this be closed in favour of #133 ?

**Comment by vlcinsky** [comment]
Closing in favour of a bit more elaborated #133
