### ISSUE TITLE
Environments variable are not properly set

### ISSUE THREAD

**Issue by leonzweig** [tiangolo/full-stack-fastapi-postgresql#89]
I am confused on how the environment get set. Simply running `docker-compose up -d` seems to be running the [docker-compose.test.yml](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/docker-compose.test.yml) file. But it will not load the env-postgres.env so I am not able to login into the frontend. I don't see a regular docker-compose.yml file. What docker-compose command do I use to stand up a dev environment?

**Comment by Dectinc** [comment]
Default docker-compose configuration files come from `.env` in the root directory of the generated project.

```
COMPOSE_FILE=docker-compose.test.yml:docker-compose.shared.admin.yml:docker-compose.shared.base-images.yml:docker-compose.shared.depends.yml:docker-compose.shared.env.yml:docker-compose.dev.build.yml:docker-compose.dev.command.yml:docker-compose.dev.env.yml:docker-compose.dev.labels.yml:docker-compose.dev.networks.yml:docker-compose.dev.ports.yml:docker-compose.dev.volumes.yml
```

and environment variables are imported with `env_file` configuration in `docker-compose.shared.env.yml`

**Comment by tiangolo** [comment]
Thanks for the help here @Dectinc !

@leonzweig yeah, what @Dectinc said.

On the other side, I'm planning to simplify all those Docker Compose files: https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/143

**Comment by tiangolo** [comment]
I just refactored a lot all the Docker Compose files and the setup.

There are now only 2 files, `docker-compose.yml` and `docker-compose.override.yml`.

And the env vars file is now only on `.env`, so it should (hopefully :crossed_fingers: ) be a lot easier to understand and debug.

The generated README is also updated taking into account all these updates.
