### ISSUE TITLE
backend does not start

### ISSUE THREAD

**Issue by monatis** [tiangolo/full-stack-fastapi-postgresql#90]
`docker-compose up -d` starts each one of the services, but `backend` service fails with the following:

`docker-compose logs backend`

```
Attaching to iaas_backend_1
[36mbackend_1        |[0m Checking for script in /app/prestart.sh
[36mbackend_1        |[0m There is no script /app/prestart.sh
[36mbackend_1        |[0m INFO: Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[36mbackend_1        |[0m INFO: Started reloader process [1]
[36mbackend_1        |[0m ERROR: Error loading ASGI app. Import string ":app" must be in format "<module>:<attribute>".
[36mbackend_1        |[0m INFO: Stopping reloader process [1]
```

I tried to get into the `backend`'s bash to try debugging, but it also fails:

`docker-compose exec backend bash`

`ERROR: No container found for backend_1`

**Comment by monatis** [comment]
I commented and uncommented commands in `docker-compose.dev.command.yml` so that `backend` should be able to run indefinitely, and now could get into that container with `docker-compose exec backend bash`. The problem is that `/app` directory is empty in the container. Something prevents it from mounting volumes on the host machine. What might be the reason for that? A permission issue?

**Comment by monatis** [comment]
It seems that this error relates to WSL, not to any particular Docker image / container. I resolved it, closing the issue.

**Comment by joehoeller** [comment]
**Problem persists:**

```
Request URL: http://localhost/docs
Request Method: GET
Status Code: 404 Not Found
```

**_AND_**

```
Request URL: http://localhost/api/v1/login/access-token
Request Method: POST
Status Code: 404 Not Found
Remote Address: [::1]:80
```

**Comment by monatis** [comment]
Hi @joehoeller, in my case it was an issue related to Windows Subsystem for Linux. It seems that WSL doesn't properly handle volumes, so I moved my project to regular Windows and it works now. Please try to make sure that `./backend/app` is properly mounted as a volume inside the container.

**Comment by joehoeller** [comment]
No I am on Linux/Ubuntu. So, should I comment it?

**Comment by joehoeller** [comment]
Its like the DB on PORT 5432 (Postgres) doesnt evemn generate, it looks
like it doesnt exist

**Comment by joehoeller** [comment]
Yo — I’m a pretty upfront person and support all my GitHib projects, so
with that said, here’s to keeping it real:

Why don’t you clone the repo and try running it by going thru the steps and
fix your broken repo?

This problem isn’t fixed.

**Comment by robido** [comment]
I struggled with this issue a while... tried to mount files in a seperate drive away from Windows C, tried running Docker in Windows mode, tried all the fixes offered here, none worked.

What worked for me was to do the same as in this issue:
https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/41

I know the solution says its a cookie cutter issue, but the line endings are still wrong in the source of this repo. Should I do a PR?

**Comment by AkashV10** [comment]
I had the same issue on windows.
Fixed with running `find . -type f -exec dos2unix {} \;` in git bash under the project root. 
https://stackoverflow.com/questions/7068179/convert-line-endings-for-whole-directory-tree-git
This will convert all files to LF.

**Comment by tiangolo** [comment]
Thanks @monatis for reporting back and closing the issue :+1: 

Thanks @AkashV10 for the tip. If anyone else is still having problems, please create a new issue (unless you already did :sweat_smile: )

**Comment by danielbf92** [comment]
Hello, I will need your help, I am having the problem you had from the beginning in api send me this:

`ERROR: Error loading ASGI app. Import string ": app" must be in format "<module>: <attribute>".`

**Comment by danielbf92** [comment]
@tiangolo
