### ISSUE TITLE
could you specify version in Pipfile file?

### ISSUE THREAD

**Issue by orange888** [tiangolo/full-stack-fastapi-postgresql#95]
Please make sure to version control using Pipfile, my generated Pipfile is like the followings:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
mypy = "*"
black = "*"
jupyter = "*"
isort = "*"
autoflake = "*"
flake8 = "*"
pytest = "*"
vulture = "*"

[packages]
fastapi = "*"
uvicorn = "*"
pyjwt = "*"
python-multipart = "*"
email-validator = "*"
requests = "*"
celery = "*"
passlib = {extras = ["bcrypt"],version = "*"}
tenacity = "*"
pydantic = "*"
emails = "*"
raven = "*"
gunicorn = "*"
jinja2 = "*"
psycopg2-binary = "*"
alembic = "*"
sqlalchemy = "*"

[requires]
python_version = "3.6"

[pipenv]
allow_prereleases = true

```

Thanks.

**Comment by tiangolo** [comment]
Actually, I'm going to remove Pipenv and migrate to Poetry as it's being better maintained and supports more use cases.

But feel free to use any system you prefer and modify your projects to your liking! :nerd_face: :heavy_check_mark: 

I'm gonna close this issue now. But feel free to add more comments or create new issues.

**Comment by tiangolo** [comment]
The latest version is now based on Poetry :rocket:
