### ISSUE TITLE
Backend doesnt build

### ISSUE THREAD

**Issue by joehoeller** [tiangolo/full-stack-fastapi-postgresql#96]
Problem persists when after you add admin and pass for user in cookiecutter steps, DB and connections fail. Browser console also outputs this:

Request URL: http://localhost/docs
Request Method: GET
Status Code: 404 Not Found

AND

Request URL: http://localhost/api/v1/login/access-token
Request Method: POST
Status Code: 404 Not Found
Remote Address: [::1]:80

**Comment by acidjunk** [comment]
This seems to be related to #90 (which contains a workaround)

**Comment by acidjunk** [comment]
Had the same issue: #84 seems to be related. (at least in my case: the upgrade to pydantic 1.0.0 changes some imports). The workaround in #84 works to get a running backend but it will yield new errors when you try to edit a user or when trying to reset a user. I will try to create a PR for that.

**Comment by joehoeller** [comment]
@acidjunk Should i do a git pull to update?

**Comment by tiangolo** [comment]
Thanks for the help @acidjunk ! :cake: 

If this was related to those issues, this should be fixed in `master`, so you could re-generate the project with the new changes.

Otherwise, the best way to debug it would be to check your logs.
